In [1]:
import pandas as pd
import numpy as np
import os
import optuna

from sklearn.cluster import KMeans
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import TargetEncoder
from sklearn.pipeline import Pipeline
from sklearn.base import clone
from sklearn.model_selection import TimeSeriesSplit, cross_validate, GridSearchCV
from sklearn.ensemble import RandomForestRegressor, StackingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import Ridge

import json
from scipy.optimize import minimize
from sklearn.metrics import root_mean_squared_error

In [2]:
# 원본 train 데이터
df = pd.read_csv('train_call.csv', encoding = 'cp949')

# 결측치 명시
df = df.replace(-99.0, None)

# 컬럼명 정리
df.columns = df.columns.str.replace('^call119_train\\.', '', regex = True)

# 데이터 추가

### 구별 이전 달의 주민등록인구

In [170]:
# 'address_gu' 별 주민등록인구: KOSIS > 지역통계 > 인구 및 사회 (사회조사 외) > 부산광역시 > 부산광역시주민등록인구통계 > 주민등록인구총괄 > 부산광역시 전체 세대 및 인구개황
gu_pop = pd.read_csv('gu_pop.csv', encoding = 'cp949', dtype = {'시점': str}, na_values = '-')

# 컬럼명 정리
gu_pop = gu_pop.rename(
    columns = {'시점': 'tm',
               '구·군별': 'address_gu',
               '읍면동수 (개)': 'sub_address_count',
               '세대수 (세대)': 'gu_household',
               '인구수  (명)': 'gu_pop',
               '남자인구수 (명)': 'gu_male_pop',
               '여자인구수 (명)': 'gu_female_pop',
               '시전체 인구에 대한 구성비 (%)': 'gu_pop_ratio',
               '면적 (㎢)': 'gu_area',
               '인구밀도 (명/㎢)': 'gu_density'}
)

# 날짜 컬럼 정리
gu_pop['tm'] = pd.to_datetime(gu_pop['tm'].astype(str), format = '%Y.%m')
gu_pop['year'] = gu_pop['tm'].dt.year.astype(int)
gu_pop['month'] = gu_pop['tm'].dt.month.astype(int)
gu_pop = gu_pop.drop('tm', axis = 1)

# 불필요한 날짜 제거
gu_pop = gu_pop[gu_pop['month'].isin(range(4, 10))].reset_index(drop = True)

# 이전 달의 정보를 현재의 feature로 이동
gu_pop['month'] = gu_pop['month'] + 1

# 회의 후 drop
gu_pop = gu_pop.drop(
    ['sub_address_count', 'gu_household', 'gu_pop', 'gu_male_pop', 'gu_female_pop'],
    axis = 1
)

# 저장
gu_pop.to_csv('merge0.csv', index = False, encoding = 'cp949')

# 조회
gu_pop

    address_gu  gu_pop_ratio  gu_area  gu_density  year  month
0           중구           1.3     2.83       15523  2020      5
1           서구           3.2    13.98        7849  2020      5
2           동구           2.7     9.87        9321  2020      5
3          영도구           3.4    14.20        8272  2020      5
4         부산진구          10.4    29.67       12132  2020      5
..         ...           ...      ...         ...   ...    ...
475        강서구           4.5   182.16         823  2024     10
476        연제구           6.4    12.11       17634  2024     10
477        수영구           5.2    10.22       17106  2024     10
478        사상구           6.2    36.11        5719  2024     10
479        기장군           5.4   218.33         822  2024     10

[480 rows x 6 columns]

### 읍면동별 이전 달의 주민등록인구

In [171]:
# --------------------------------------------------
# 'sub_address' 별 주민등록인구: KOSIS > 지역통계 > 인구 및 사회 (사회조사 외) > 부산광역시 > 부산광역시주민등록인구통계 > 주민등록인구총괄 > 구·군 및 읍·면·동 세대와 인구
# --------------------------------------------------
# 행정동 변경으로 인해, 일부 지역은 평균치로 대체함
# --------------------------------------------------
sub_pop = pd.read_csv('sub_pop.csv', encoding = 'cp949', dtype = {'시점': str}, na_values = '-')

# 불필요한 컬럼 삭제
sub_pop = sub_pop.drop(['내외국인별', 'Unnamed: 7'], axis = 1)


# 컬럼명 정리
sub_pop = sub_pop.rename(
    columns = {'구·군별': 'sub_address',
               '시점': 'tm',
               '세대수[세대]': 'sub_household',
               '인구[명]': 'sub_pop',
               '남자인구[명]': 'sub_male_pop',
               '여자인구[명]': 'sub_female_pop'}
)

# 'address_gu' 컬럼 추가 (송정동은 강서구와 해운대구에 모두 존재)
gu_set = set(df['address_gu'])
sub_pop['address_gu'] = sub_pop['sub_address'].where(
    sub_pop['sub_address'].isin(gu_set)
)
sub_pop['address_gu'] = sub_pop['address_gu'].ffill()

# 날짜 컬럼 정리
sub_pop['tm'] = sub_pop['tm'].str.replace(
    r'\s[가-힣]+', '', regex = True
)
sub_pop['tm'] = pd.to_datetime(sub_pop['tm'].astype(str), format = '%Y.%m')
sub_pop['year'] = sub_pop['tm'].dt.year.astype(int)
sub_pop['month'] = sub_pop['tm'].dt.month.astype(int)
sub_pop = sub_pop.drop('tm', axis = 1)

# 불필요한 날짜 제거
sub_pop = sub_pop[sub_pop['month'].isin(range(4, 10))].reset_index(drop = True)

# 이전 달의 정보를 현재의 feature로 이동
sub_pop['month'] = sub_pop['month'] + 1

# 'sub_address'가 'address_gu'인 자료 제거
sub_pop = sub_pop[~sub_pop['sub_address'].isin(gu_set)]



# --------------------------------------------------
# 'sub_address' 별 1인 가구 수: KOSIS > 지역통계 > 인구 및 사회 (사회조사 외) > 부산광역시 > 부산광역시주민등록인구통계 > 주민등록인구총괄 > 읍·면·동별 세대원수별 세대수
# --------------------------------------------------
# 행정동 변경으로 인한 결측치를 함께 대체하기 위해 통합
# --------------------------------------------------
sub_single = pd.read_csv('sub_single.csv', encoding = 'cp949', dtype = {'시점': str}, na_values = '-')

# 컬럼명 정리
sub_single = sub_single.rename(
    columns = {'시점': 'tm',
               '구·군별(1)': 'address_gu',
               '구·군별(2)': 'sub_address',
               '1인': 'sub_single'}
)

# 날짜 컬럼 정리
sub_single['tm'] = pd.to_datetime(sub_single['tm'].astype(str), format = '%Y.%m')
sub_single['year'] = sub_single['tm'].dt.year.astype(int)
sub_single['month'] = sub_single['tm'].dt.month.astype(int)
sub_single = sub_single.drop('tm', axis = 1)

# 불필요한 날짜 제거
sub_single = sub_single[sub_single['month'].isin(range(4, 10))].reset_index(drop = True)

# 이전 달의 정보를 현재의 feature로 이동
sub_single['month'] = sub_single['month'] + 1

# --------------------------------------------------
# 통합
# --------------------------------------------------
sub_pop = sub_pop.merge(sub_single, how = 'left', on = ['year', 'month', 'address_gu', 'sub_address'])

# --------------------------------------------------
# 행정동 변화가 없는 'sub_address'
# --------------------------------------------------
# ! ! !단, '일광면'과 '정관면'은 train 및 test 데이터를 수정 ! ! !
# --------------------------------------------------
A0 = sub_pop[
    ~sub_pop['sub_address']
    .isin([
        '중앙동', '영주1동', '영주2동', '광복동',
        '부민동', '충무동', '남항동', '부전1동',
        '부전2동', '수민동', '복산동', '반송1동',
        '반송2동', '금사회동동', '청룡노포동', '선두구동',
        '부곡1동', '부곡2동', '부곡3동', '부곡4동',
        '녹산동', '송정동', '가덕도동', '가락동',
        '대저1동', '대저2동'
    ])
]
A0 = A0.copy()
A0['sub_address'] = A0['sub_address'].str.replace(
    '[0-9]+(?=동)', '', regex = True
)
A0 = A0.groupby(['year', 'month', 'address_gu', 'sub_address']).sum().reset_index()
A1 = sub_pop[
    sub_pop['sub_address']
    .isin(['대저1동', '대저2동'])
]
A = pd.concat([A0, A1], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: 대창동 <- (중앙동, 영주동) / 중앙동 <- 중앙동 / (대창동, 영주동) <- 영주동
# --------------------------------------------------
B0 = sub_pop[
    sub_pop['sub_address']
    .isin(['중앙동', '영주1동', '영주2동'])
]

B0 = B0.copy()
B0['sub_address'] = B0['sub_address'].str.replace(
    '[0-9]+(?=동)', '', regex = True
)
B0 = B0.groupby(['year', 'month', 'address_gu', 'sub_address']).sum().reset_index()

# 대창동
B1 = B0.copy()
B1 = B1.groupby(['year', 'month', 'address_gu'])[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]].mean().reset_index()
B1['sub_address'] = '대창동'

# 중앙동
B2 = B0.copy()
B2 = B2.loc[B2['sub_address'] == '중앙동', :] 
B2[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = B2[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2

# 영주동
B3 = B0.copy()
B3 = B3.loc[B3['sub_address'] == '영주동', :] 
B3[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = B3[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2

# 통합
B = pd.concat([B1, B2, B3], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (신창동, 광복동, 창선동) <- 광복동
# --------------------------------------------------
C0 = sub_pop[
    sub_pop['sub_address']
    .isin(['광복동'])
]

# 광복동
C1 = C0.copy() 
C1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = C1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 3

# 신창동
C2 = C1.copy() 
C2['sub_address'] = '신창동'

# 창선동
C3 = C1.copy() 
C3['sub_address'] = '창선동'

# 통합
C = pd.concat([C1, C2, C3], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (부민동, 부용동) <- 부민동
# --------------------------------------------------
D0 = sub_pop[
    sub_pop['sub_address']
    .isin(['부민동'])
]

# 부민동
D1 = D0.copy()
D1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = D1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2

# 부용동
D2 = D1.copy()
D2['sub_address'] = '부용동'

# 통합
D = pd.concat([D1, D2], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (충무동, 토성동) <- 충무동
# --------------------------------------------------
E0 = sub_pop[
    sub_pop['sub_address']
    .isin(['충무동'])
]

# 충무동
E1 = E0.copy()
E1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = E1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2

# 토성동
E2 = E1.copy()
E2['sub_address'] = '토성동'

# 통합
E = pd.concat([E1, E2], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (남항동, 대교동, 대평동) <- 남항동
# --------------------------------------------------
F0 = sub_pop[
    sub_pop['sub_address']
    .isin(['남항동'])
]

# 남항동
F1 = F0.copy()
F1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = F1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 3

# 대교동
F2 = F1.copy()
F2['sub_address'] = '대교동'

# 대평동
F3 = F1.copy()
F3['sub_address'] = '대평동'

# 통합
F = pd.concat([F1, F2, F3], ignore_index = True)

# 저장
#sub_pop.to_csv('merge1.csv', index = False, encoding = 'cp949')

# --------------------------------------------------
# 행정동 변화: (부전동, 범전동) <- 부전1동, 부전동 <- 부전2동
# --------------------------------------------------
G0 = sub_pop[
    sub_pop['sub_address']
    .isin(['부전1동', '부전2동'])
]

# 부전동
G1 = G0.copy()
G1 = G1.groupby(['year', 'month', 'address_gu'])[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]].mean().reset_index()
G1['sub_address'] = '부전동'

# 범전동
G2 = sub_pop[
    sub_pop['sub_address']
    .isin(['부전1동'])
]
G2 = G2.copy()
G2[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = G2[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2
G2['sub_address'] = '범전동'

# 통합
G = pd.concat([G1, G2], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (낙민동, 수안동) <- 수민동
# --------------------------------------------------
H0 = sub_pop[
    sub_pop['sub_address']
    .isin(['수민동'])
]

# 낙민동
H1 = H0.copy()
H1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = H1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2
H1['sub_address'] = '낙민동'

# 수안동
H2 = H1.copy()
H2['sub_address'] = '수안동'

# 통합
H = pd.concat([H1, H2], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (복천동, 칠산동) <- 복산동
# --------------------------------------------------
I0 = sub_pop[
    sub_pop['sub_address']
    .isin(['복산동'])
]

# 복천동
I1 = I0.copy()
I1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = I1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2
I1['sub_address'] = '복천동'

# 칠산동
I2 = I1.copy()
I2['sub_address'] = '칠산동'

# 통합
I = pd.concat([I1, I2], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (반송동, 석대동) <- 반송1동, 반송동 <- 반송2동
# --------------------------------------------------
J0 = sub_pop[
    sub_pop['sub_address']
    .isin(['반송1동', '반송2동'])
]

# 반송동
J1 = J0.copy()
J1 = J1.groupby(['year', 'month', 'address_gu'])[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]].mean().reset_index()
J1['sub_address'] = '반송동'

# 석대동
J2 = sub_pop[
    sub_pop['sub_address']
    .isin(['반송1동'])
]
J2 = J2.copy()
J2[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = J2[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2
J2['sub_address'] = '석대동'

# 통합
J = pd.concat([J1, J2], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (금사동, 회동동) <- 금사회동동
# --------------------------------------------------
K0 = sub_pop[
    sub_pop['sub_address']
    .isin(['금사회동동'])
]

# 금사동
K1 = K0.copy()
K1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = K1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2
K1['sub_address'] = '금사동'

# 회동동
K2 = K1.copy()
K2['sub_address'] = '회동동'

# 통합
K = pd.concat([K1, K2], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (청룡동, 노포동) <- 청룡노포동
# --------------------------------------------------
L0 = sub_pop[
    sub_pop['sub_address']
    .isin(['청룡노포동'])
]

# 청룡동
L1 = L0.copy()
L1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = L1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2
L1['sub_address'] = '청룡동'

# 노포동
L2 = L1.copy()
L2['sub_address'] = '노포동'

# 통합
L = pd.concat([L1, L2], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (선동, 두구동) <- 선두구동
# --------------------------------------------------
M0 = sub_pop[
    sub_pop['sub_address']
    .isin(['선두구동'])
]

# 선동
M1 = M0.copy()
M1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = M1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2
M1['sub_address'] = '선동'

# 두구동
M2 = M1.copy()
M2['sub_address'] = '두구동'

# 통합
M = pd.concat([M1, M2], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: 오륜동 <- 부곡3동, 부곡동 <- (부곡1동, 부곡2동, 부곡3동, 부곡4동)
# --------------------------------------------------
# 오륜동
N1 = sub_pop[
    sub_pop['sub_address']
    .isin(['부곡3동'])
]
N1 = N1.copy()
N1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = N1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 2
N1['sub_address'] = '오륜동'

# 부곡동
N2 = sub_pop[
    sub_pop['sub_address']
    .isin(['부곡1동', '부곡2동', '부곡4동'])
]
N2 = N2.copy()
N2 = pd.concat([N1, N2])
N2 = N2.groupby(['year', 'month', 'address_gu'])[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]].sum().reset_index()
N2['sub_address'] = '부곡동'

# 통합
N = pd.concat([N1, N2], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (녹산동, 구랑동, 미음동, 범방동, 생곡동, 화전동, 지사동, 신호동, 송정동) <- 녹산동, 송정동 <- 송정동
# --------------------------------------------------
# ! ! ! 강서구의 송정동 (해운대에도 송정동이 있음) ! ! !
# --------------------------------------------------
# 녹산동
O1 = sub_pop[
    sub_pop['sub_address']
    .isin(['녹산동'])
]
O1 = O1.copy()
O1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = O1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 9

# 구랑동, 미음동, 범방동, 생곡동, 화전동, 지사동, 신호동
O2 = O1.copy()
O2['sub_address'] = '구랑동'
O3 = O1.copy()
O3['sub_address'] = '미음동'
O4 = O1.copy()
O4['sub_address'] = '범방동'
O5 = O1.copy()
O5['sub_address'] = '생곡동'
O6 = O1.copy()
O6['sub_address'] = '화전동'
O7 = O1.copy()
O7['sub_address'] = '지사동'
O8 = O1.copy()
O8['sub_address'] = '신호동'

# 강서구 송정동
O9 = O1.copy()
O9['sub_address'] = '송정동'

# 통합
O = pd.concat([O1, O2, O3, O4, O5, O6, O7, O8, O9], ignore_index = True)

# --------------------------------------------------
# 해운대구 송정동
# --------------------------------------------------
P = sub_pop[
    (sub_pop['sub_address']
    .isin(['송정동'])) &
    (sub_pop['address_gu'] == '해운대구')
]
P = P.reset_index(drop = True)

# --------------------------------------------------
# 행정동 변화: (눌차동, 대항동, 동선동, 성북동, 천성동) <- 가덕도동
# --------------------------------------------------
Q0 = sub_pop[
    sub_pop['sub_address']
    .isin(['가덕도동'])
]

# 눌차동
Q1 = Q0.copy()
Q1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = Q1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 5
Q1['sub_address'] = '눌차동'

# 대항동, 동선동, 성북동, 천성동
Q2 = Q1.copy()
Q2['sub_address'] = '대항동'
Q3 = Q1.copy()
Q3['sub_address'] = '동선동'
Q4 = Q1.copy()
Q4['sub_address'] = '성북동'
Q5 = Q1.copy()
Q5['sub_address'] = '천성동'

# 통합
Q = pd.concat([Q1, Q2, Q3, Q4, Q5], ignore_index = True)

# --------------------------------------------------
# 행정동 변화: (봉림동, 식만동, 죽동동, 죽림동) <- 가락동
# --------------------------------------------------
R0 = sub_pop[
    sub_pop['sub_address']
    .isin(['가락동'])
]

# 봉림동
R1 = R0.copy()
R1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] = R1[[
    'sub_household', 'sub_pop', 'sub_male_pop', 'sub_female_pop', 'sub_single'
]] / 4
R1['sub_address'] = '봉림동'

# 식만동, 죽동동, 죽림동
R2 = R1.copy()
R2['sub_address'] = '식만동'
R3 = R1.copy()
R3['sub_address'] = '죽동동'
R4 = R1.copy()
R4['sub_address'] = '죽림동'

# 통합
R = pd.concat([R1, R2, R3, R4], ignore_index = True)

# --------------------------------------------------
# 통합
# --------------------------------------------------
sub_pop_imputed = pd.concat([A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R], ignore_index = True)

# --------------------------------------------------
# 저장
# --------------------------------------------------
sub_pop_imputed.to_csv('merge1.csv', index = False, encoding = 'cp949')

# --------------------------------------------------
# 조회
# --------------------------------------------------
sub_pop_imputed

,year,month,address_gu,sub_address,sub_household,sub_pop,sub_male_pop,sub_female_pop,sub_single
0,2020,5,강서구,강동동,2658.00,4772.00,2587.00,2185.00,1507.00
1,2020,5,강서구,명지동,26189.00,74642.00,37224.00,37418.00,5289.00
2,2020,5,금정구,구서동,20971.00,53931.00,25756.00,28175.00,5503.00
3,2020,5,금정구,금성동,491.00,1118.00,545.00,573.00,198.00
4,2020,5,금정구,남산동,13904.00,31122.00,15082.00,16040.00,5580.00
...,...,...,...,...,...,...,...,...,...
4045,2024,6,강서구,죽림동,312.75,556.00,306.75,249.25,174.75
4046,2024,7,강서구,죽림동,312.50,554.50,306.50,248.00,175.50
4047,2024,8,강서구,죽림동,313.75,553.25,306.25,247.00,177.25
4048,2024,9,강서구,죽림동,312.50,552.00,304.75,247.25,175.75
4049,2024,10,강서구,죽림동,311.75,550.50,305.25,245.25,176.75

### 구별 이전 달의 고령인구

In [173]:
# 'address_gu' 별 65세 이상 고령인구: KOSIS > 지역통계 > 인구 및 사회 (사회조사 외) > 부산광역시 > 부산광역시주민등록인구통계 > 구·군별 연령별 현황 > 구·군별 연령별(5세) 인구
gu_old = pd.read_csv('gu_old.csv', encoding = 'cp949', dtype = {'시점': str}, na_values = '-')

# 불필요한 컬럼 삭제
gu_old = gu_old.drop('연령별(1)', axis = 1)

# 컬럼명 정리
gu_old = gu_old.rename(
    columns = {'시점': 'tm',
               '구군별(1)': 'address_gu',
               '계': 'gu_old',
               '남자': 'gu_male_old',
               '여자': 'gu_female_old'}
)

# 날짜 컬럼 정리
gu_old['tm'] = pd.to_datetime(gu_old['tm'].astype(str), format = '%Y.%m')
gu_old['year'] = gu_old['tm'].dt.year.astype(int)
gu_old['month'] = gu_old['tm'].dt.month.astype(int)
gu_old = gu_old.drop('tm', axis = 1)

# 불필요한 날짜 제거
gu_old = gu_old[gu_old['month'].isin(range(4, 10))].reset_index(drop = True)

# 이전 달의 정보를 현재의 feature로 이동
gu_old['month'] = gu_old['month'] + 1

# 저장
gu_old.to_csv('merge2.csv', index = False, encoding = 'cp949')

# 조회
gu_old

    address_gu  gu_old  gu_male_old  gu_female_old  year  month
0           중구   11098         4759           6339  2020      5
1           서구   26702        11276          15426  2020      5
2           동구   23069         9617          13452  2020      5
3          영도구   30833        13087          17746  2020      5
4         부산진구   68930        29678          39252  2020      5
..         ...     ...          ...            ...   ...    ...
475        강서구   21179        10085          11094  2024     10
476        연제구   48340        20991          27349  2024     10
477        수영구   43867        18671          25196  2024     10
478        사상구   47888        21723          26165  2024     10
479        기장군   34035        14687          19348  2024     10

[480 rows x 6 columns]

### 신고가 일어난 가장 최근 날까지의 신고 카테고리별 누적 건수 및 비율

In [174]:
# --------------------------------------------------
# 신고가 일어난 가장 최근 날까지의 신고 카테고리별 누적 건수 및 비율: 'train_cat.csv', 'test_cat119.csv'
# --------------------------------------------------
# ! ! ! 2020년은 NaN이 너무 많아져서 그냥 해당 년도의 자료를 사용 ! ! !
# --------------------------------------------------
# ! ! ! 'call_count'가 없는 2024년은 모두 2020-2023년의 median으로 대체 ! ! ! 
# --------------------------------------------------
cat1 = pd.read_csv('train_cat.csv', encoding = 'cp949')
cat2 = pd.read_csv('test_cat119.csv', encoding = 'cp949')

# 컬럼명 정리
cat1.columns = cat1.columns.str.replace('^cat119_train\\.', '', regex = True)
cat2 = cat2.rename(
    columns = {'TM': 'tm', 'STN': 'stn'}
)

# 불필요한 컬럼 정리
cat1 = cat1.drop(['Unnamed: 0', 'address_city', 'stn'], axis = 1)
cat2 = cat2.drop(['address_city', 'stn'], axis = 1)

# 2024년 'sub_cat' 별 'call_count' imputation
# ! ! ! 2020-2023년에는 기타>상황출동만 존재하지만, 2024년에는 구조>상황출동이 하나 존재함. 'cat' 무시하고 기타>상황출동의 값으로 imputation ! ! !
impute2024 = cat1.groupby(['sub_cat'])['call_count'].median().reset_index()
cat2 = cat2.merge(impute2024, how = 'left', on = ['sub_cat'])

# 2020-2024 통합
cat = pd.concat([cat1, cat2], ignore_index = True)

# 날짜 컬럼 정리
cat['tm'] = pd.to_datetime(cat['tm'].astype(str), format = '%Y%m%d')
cat['tm'] = cat['tm'] + pd.Timedelta(days = 1) # (1) 대희 딸깎
cat['year'] = cat['tm'].dt.year.astype(int)
cat['month'] = cat['tm'].dt.month.astype(int)
cat['day'] = cat['tm'].dt.day.astype(int)
cat = cat.drop('tm', axis = 1)

# 행정구 통일
cat['sub_address'] = cat['sub_address'].replace({'일광면': '일광읍', '정관면': '정관읍'})

In [175]:
# --------------------------------------------------
# 'cat' 비율 및 건수 계산
# --------------------------------------------------
# 'cat'별 'call_count' 합계
pivot_cat = cat.copy().groupby([
    'year', 'month', 'day', 'address_gu', 'sub_address', 'cat'
])['call_count'].sum().reset_index()

# 'cat'을 컬럼으로 pivot
pivot_cat = pivot_cat.pivot_table(
    index = ['year', 'month', 'day', 'address_gu', 'sub_address'],
    columns = 'cat',
    values = 'call_count',
    fill_value = 0
).reset_index()

# 'call_sum' (날짜 + 지역 별 총 'call _count') 계산
cat_cols = pivot_cat.columns.difference(
    ['year', 'month', 'day', 'address_gu', 'sub_address']
).to_list()
pivot_cat['call_sum'] = pivot_cat[cat_cols].sum(axis = 1)

# 날짜 범위 만들기
date_range = pd.date_range(start = '2020-05-01', end = '2024-10-31', freq='D')
date_df = pd.DataFrame({
    'year': date_range.year,
    'month': date_range.month,
    'day': date_range.day
})

# Unique 'address_gu' + 'sub_address' 조합 추출
sub_addrs = pivot_cat[['address_gu', 'sub_address']].drop_duplicates()
sub_addrs = sub_addrs.sort_values(['address_gu', 'sub_address']).reset_index(drop = True)

# 'year' + 'month' + 'day' + 'address_gu' + 'sub_address' 조합 생성
full_index = date_df.merge(sub_addrs, how = 'cross')

# 생성된 모든 조합과 'pivot_cat'을 병합
pivot_cat_filled = full_index.merge(
    pivot_cat, 
    on = ['year', 'month', 'day', 'address_gu', 'sub_address'],
    how = 'left'
)

# 빈 날짜 + 지역의 신고 건수 결측치를 0으로 설정
pivot_cat_filled.fillna(0, inplace = True)

# 정렬
pivot_cat_filled = pivot_cat_filled.sort_values([
    'address_gu', 'sub_address', 'year', 'month', 'day'
]).reset_index(drop = True)

# 'call_sum' (누적 'call _count') 누적합 계산
pivot_cat_filled['cum_call_sum'] = pivot_cat_filled.groupby([
    'address_gu', 'sub_address' # (2) 대희야 여기 'address_gu'가 빠져서 송정동 ratio 합이 1이 안되서 추가했다
])['call_sum'].cumsum()

# 'cat' 별 'call_sum' 계산
for col in cat_cols:
    cum_col = f'cum_{col}'
    pivot_cat_filled[cum_col] = pivot_cat_filled.groupby([
        'address_gu', 'sub_address'
    ])[col].cumsum()

# 누적 비율 계산
for col in cat_cols:
    pivot_cat_filled[f'cum_{col}_ratio'] = pivot_cat_filled[f'cum_{col}'] / pivot_cat_filled['cum_call_sum']

# 비율 결측치를 0으로 설정
pivot_cat_filled.fillna(0, inplace = True)

In [176]:
# --------------------------------------------------
# 'sub_cat' 비율 및 건수 계산
# --------------------------------------------------
# 'sub_cat'별 'call_count' 합계
pivot_subcat = cat.copy().groupby([
    'year', 'month', 'day', 'address_gu', 'sub_address', 'sub_cat'
])['call_count'].sum().reset_index()

# 'sub_cat'을 컬럼으로 pivot
pivot_subcat = pivot_subcat.pivot_table(
    index=['year', 'month', 'day', 'address_gu', 'sub_address'],
    columns='sub_cat',
    values='call_count',
    fill_value=0
).reset_index()

# 'call_sum' (날짜 + 지역 별 총 'call _count') 계산
subcat_cols = pivot_subcat.columns.difference(
    ['year', 'month', 'day', 'address_gu', 'sub_address']
).to_list()
pivot_subcat['call_sum'] = pivot_subcat[subcat_cols].sum(axis = 1)

# 'year' + 'month' + 'day' + 'address_gu' + 'sub_address' 조합과 'pivot_subcat'을 병합
pivot_subcat_filled = full_index.merge(
    pivot_subcat, 
    on = ['year', 'month', 'day', 'address_gu', 'sub_address'],
    how = 'left'
)

# 빈 날짜 + 지역의 신고 건수 결측치를 0으로 설정
pivot_subcat_filled.fillna(0, inplace = True)

# 정렬
pivot_subcat_filled = pivot_subcat_filled.sort_values([
    'address_gu', 'sub_address', 'year', 'month', 'day'
]).reset_index(drop = True)

# 'call_sum' (누적 'call _count') 누적합 계산
pivot_subcat_filled['cum_call_sum'] = pivot_subcat_filled.groupby([
    'address_gu', 'sub_address'
])['call_sum'].cumsum()

# 'sub_cat'별 'call_sum' 계산
for col in subcat_cols:
    cum_col = f'cum_{col}'
    pivot_subcat_filled[cum_col] = pivot_subcat_filled.groupby([
        'address_gu', 'sub_address'
    ])[col].cumsum()

# 누적 비율 계산
for col in subcat_cols:
    pivot_subcat_filled[f'cum_{col}_ratio'] = pivot_subcat_filled[f'cum_{col}'] / pivot_subcat_filled['cum_call_sum']

# 비율 결측치를 0으로 설정
pivot_subcat_filled.fillna(0, inplace = True)

In [177]:
# --------------------------------------------------
# 병합
# --------------------------------------------------
# 혹시 모르니 동일한 순서로 정렬
sort_keys = ['year', 'month', 'day', 'address_gu', 'sub_address']
pivot_cat_filled = pivot_cat_filled.sort_values(by = sort_keys).reset_index(drop = True)
pivot_subcat_filled = pivot_subcat_filled.sort_values(by = sort_keys).reset_index(drop = True)

# 키 컬럼 중복 방지를 위해 'pivot_subcat_filled'에서 키 컬럼, 중복 컬럼 제외
pivot_subcat_filled_only = pivot_subcat_filled.drop(
    columns = ['year', 'month', 'day', 'address_gu', 'sub_address', 'call_sum', 'cum_call_sum'] # (3) 대희 같은 컬럼이 더 있었습니다
)

# 중복된 컬럼명 변경
pivot_subcat_filled_only = pivot_subcat_filled_only.rename(
    columns = {'cum_기타': 'cum_sub_기타',
               'cum_기타_ratio': 'cum_sub_기타_ratio',
               '기타': 'cum_sub_기타_ratio'}
) # (4) 대희 합치니까 이상한 suffix가 생기길래 확인해 보니 이름이 같은 컬럼들이 있었습니다

# 병합
pivot_df = pd.concat([pivot_cat_filled, pivot_subcat_filled_only], axis = 1)

# 불필요한 날짜 삭제
pivot_df = pivot_df[pivot_df['month'].isin(range(5, 11))].reset_index(drop = True)

# --------------------------------------------------
# 휘의 후 필요한 컬럼만 선택: 구급 기타만 'sub_cat'에서 가져감
# --------------------------------------------------
pivot_df = pivot_df.loc[:, pivot_cat_filled.columns.to_list() + ['구급기타', 'cum_구급기타', 'cum_구급기타_ratio']]
pivot_df = pivot_df.copy()

# --------------------------------------------------
# 저장
# --------------------------------------------------
pivot_df.to_csv('merge4.csv', index = False, encoding = 'cp949') 

# --------------------------------------------------
# 조회
# --------------------------------------------------
pivot_df

,year,month,day,address_gu,sub_address,구급,구조,기타,화재,call_sum,...,cum_구조,cum_기타,cum_화재,cum_구급_ratio,cum_구조_ratio,cum_기타_ratio,cum_화재_ratio,구급기타,cum_구급기타,cum_구급기타_ratio
0,2020,5,1,강서구,강동동,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
1,2020,5,1,강서구,구랑동,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
2,2020,5,1,강서구,녹산동,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
3,2020,5,1,강서구,눌차동,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
4,2020,5,1,강서구,대저1동,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124195,2024,10,31,해운대구,송정동,1.0,0.0,0.0,0.0,1.0,...,301.0,205.0,0.0,0.401891,0.355792,0.242317,0.000000,0.0,18.0,0.021277
124196,2024,10,31,해운대구,우동,1.0,0.0,0.0,0.0,1.0,...,520.0,460.0,3.0,0.644870,0.187861,0.166185,0.001084,0.0,257.0,0.092847
124197,2024,10,31,해운대구,재송동,1.0,0.0,0.0,0.0,1.0,...,130.0,45.0,2.0,0.827485,0.126706,0.043860,0.001949,0.0,100.0,0.097466
124198,2024,10,31,해운대구,좌동,2.0,0.0,0.0,0.0,2.0,...,223.0,275.0,0.0,0.680154,0.143224,0.176622,0.000000,0.0,114.0,0.073218
124199,2024,10,31,해운대구,중동,0.0,0.0,1.0,0.0,1.0,...,431.0,250.5,0.0,0.560181,0.278154,0.161665,0.000000,0.0,66.0,0.042594

### 구별 위경도와 지역 클러스터링

In [178]:
# 'address_gu'의 위경도: 국토부 브이월드 > 공간정보 다운로드 > 행정구역시군구_경계 > 위경도 추출
gu_lat_lon = pd.read_csv("gu_lat_lon.csv", encoding = 'cp949')

# address_gu 만들고 남은거 drop
gu_lat_lon['address_gu'] = gu_lat_lon['SGG_NM'].str.replace('부산광역시 ', '', regex = False)
gu_lat_lon = gu_lat_lon.drop(columns = ['ADM_SECT_C', 'SGG_NM', 'SGG_OID', 'COL_ADM_SE'])

# 클러스터 추가(Elbow, Silhouette 참고 => 4개 설정)
gu_lat_lon['gu_cluster'] = KMeans(n_clusters = 4, random_state = 42).fit_predict(
    gu_lat_lon[['gu_lat', 'gu_lon']]
)
gu_lat_lon['gu_cluster'] = gu_lat_lon['gu_cluster'].astype(object)

# 저장
gu_lat_lon.to_csv('merge6.csv', index = False, encoding = 'cp949')

# 조회
gu_lat_lon

       gu_lat      gu_lon address_gu gu_cluster
0   35.105428  129.032244         중구          2
1   35.102756  129.014967         서구          2
2   35.128321  129.044884         동구          2
3   35.078764  129.064950        영도구          2
4   35.165259  129.043064       부산진구          0
5   35.206208  129.079222        동래구          0
6   35.125320  129.094368         남구          2
7   35.229263  129.023471         북구          0
8   35.193726  129.153691       해운대구          0
9   35.088136  128.973769        사하구          2
10  35.258889  129.091550        금정구          0
11  35.137044  128.891047        강서구          1
12  35.182403  129.082992        연제구          0
13  35.161178  129.111587        수영구          0
14  35.158034  128.986596        사상구          2
15  35.297918  129.201049        기장군          3

### 읍면동별 위경도

In [179]:
# 국토부 브이월드 > 공간정보 다운로드 > 행정구역_읍면동(법정동) > QGIS 정제 > 'sub_address'의 위도 및 경도 추출
sub_lat_lon = pd.read_csv("sub_lat_lon.csv", encoding = 'cp949')

# address_gu, sub_address로 groupby해서 위경도 평균 구하기
sub_lat_lon = sub_lat_lon.groupby([
    'address_gu', 'sub_address'
])[[
    'latitude', 'longitude'
]].mean().reset_index()

# 컬럼명 변경(sub_lat, sub_lon)
sub_lat_lon = sub_lat_lon.rename(columns = {
    'latitude': 'sub_lat',
    'longitude': 'sub_lon'
})

# 저장
sub_lat_lon.to_csv('merge7.csv', index = False, encoding = 'cp949')

# 조회
sub_lat_lon

    address_gu sub_address    sub_lat     sub_lon
0          강서구         강동동  35.180478  128.918633
1          강서구         구랑동  35.127437  128.854215
2          강서구         녹산동  35.117137  128.880607
3          강서구         눌차동  35.067161  128.846220
4          강서구        대저1동  35.211084  128.966085
..         ...         ...        ...         ...
130       해운대구         송정동  35.184726  129.197424
131       해운대구          우동  35.174371  129.147893
132       해운대구         재송동  35.185757  129.128266
133       해운대구          좌동  35.184467  129.174231
134       해운대구          중동  35.162505  129.176740

[135 rows x 4 columns]

### 읍면동 별 전년도의 신고 건수 중간값

In [180]:
py = df.copy()[['tm', 'address_gu', 'sub_address', 'call_count']]
py['sub_address'] = py['sub_address'].replace({'일광면': '일광읍', '정관면': '정관읍'})

# 날짜 컬럼 정리
py['tm'] = pd.to_datetime(py['tm'].astype(str), format = '%Y%m%d')
py['year'] = py['tm'].dt.year.astype(int)
py['month'] = py['tm'].dt.month.astype(int)

# 날짜 범위
date_range = pd.date_range(start = '2020-05-01', end = '2024-10-31', freq='ME')
date_df = pd.DataFrame({
    'year': date_range.year,
    'month': date_range.month
})

# Unique 'address_gu' + 'sub_address' 조합 추출
sub_addrs = py[['address_gu', 'sub_address']].drop_duplicates()
sub_addrs = sub_addrs.sort_values(['address_gu', 'sub_address']).reset_index(drop = True)

# 'year' + 'month' + 'day' + 'address_gu' + 'sub_address' 조합 생성
full_index = date_df.merge(sub_addrs, how = 'cross')
full_index = full_index.loc[full_index['month'].isin(range(5, 11))]

# 금년 중간값
prev_year_call_med = py.groupby(
    ['year', 'month', 'address_gu', 'sub_address']
)['call_count'].median().reset_index()

# 작년 중앙값
prev_year_call_med['year'] += 1

# 병합
prev_year_call_med = full_index.merge(
    prev_year_call_med,
    how = 'left',
    on = ['year', 'month', 'address_gu', 'sub_address']
)

# 결측값은 연도에 무관한 월별 중간값으로 대체
prev_year_call_med['call_count'] = prev_year_call_med['call_count'].fillna(
    prev_year_call_med.groupby(['month', 'address_gu', 'sub_address'])['call_count'].transform('median')
)

# 대체하고도 사건이 일어나지 않아 결측치인 값은 0으로 대체
prev_year_call_med.fillna(0, inplace = True)

# 컬럼명 정리
prev_year_call_med = prev_year_call_med.rename(
    columns = {'call_count': 'prev_year_call_med'}
)

# 저장
prev_year_call_med.to_csv('merge8.csv', index = False, encoding = 'cp949')

# 조회
prev_year_call_med

      year  month address_gu sub_address  prev_year_call_med
0     2020      5        강서구         강동동                1.00
1     2020      5        강서구         구랑동                1.00
2     2020      5        강서구         녹산동                1.00
3     2020      5        강서구         눌차동                1.00
4     2020      5        강서구        대저1동                1.25
...    ...    ...        ...         ...                 ...
4045  2024     10       해운대구         송정동                1.00
4046  2024     10       해운대구          우동                3.00
4047  2024     10       해운대구         재송동                1.00
4048  2024     10       해운대구          좌동                1.50
4049  2024     10       해운대구          중동                2.00

[4050 rows x 5 columns]

### 읍면동 별 전년도 월별 신고 카테고리 비율

In [181]:
# --------------------------------------------------
# 전년도 월별 신고 카테고리별 누적 건수 및 비율: 'train_cat.csv'
# --------------------------------------------------
# ! ! ! 2020년은 NaN이 너무 많아져서 그냥 해당 년도의 자료를 사용 ! ! !
# --------------------------------------------------
# 바로 전 'year'의 'sub_address' 별 'cat' 비율
call_ratio = pd.read_csv('train_cat.csv', encoding = 'cp949')

# 컬럼명 정리
call_ratio.columns = call_ratio.columns.str.replace('^cat119_train\\.', '', regex = True)

# 날짜 컬럼 정리
call_ratio['tm'] = pd.to_datetime(call_ratio['tm'].astype(str), format = '%Y%m%d')
call_ratio['year'] = call_ratio['tm'].dt.year.astype(int)
call_ratio['month'] = call_ratio['tm'].dt.month.astype(int)

# 행정구 통일
call_ratio['sub_address'] = call_ratio['sub_address'].replace({'일광면': '일광읍', '정관면': '정관읍'})

# 'cat' 비율
r1 = call_ratio.copy().groupby(['year', 'month', 'address_gu', 'sub_address', 'cat'])['call_count'].sum().reset_index()
r1_tot = call_ratio.copy().groupby(['year', 'month', 'address_gu','sub_address'])['call_count'].sum().reset_index()
r1['year'] = r1['year'] + 1
r1_tot['year'] = r1_tot['year'] + 1

r1 = r1.merge(r1_tot, how = 'left', on = ['year', 'month', 'address_gu', 'sub_address'])
r1['ratio'] = r1['call_count_x'] / r1['call_count_y']

r1 = r1.pivot(index = ['year', 'month', 'address_gu', 'sub_address'], columns = 'cat', values = 'ratio').reset_index()
r1 = r1.fillna(0)
r1.columns = ['year', 'month', 'address_gu', 'sub_address'] + [f'prev_year_{col}' for col in r1.columns[4: ]]

In [182]:
# 바로 전 'year'의 'sub_address' 별 'sub_cat' 비율
r2 = call_ratio.copy().groupby(['year', 'month', 'address_gu', 'sub_address', 'sub_cat'])['call_count'].sum().reset_index()
r2_tot = call_ratio.copy().groupby(['year', 'month', 'address_gu','sub_address'])['call_count'].sum().reset_index()
r2['year'] = r2['year'] + 1
r2_tot['year'] = r2_tot['year'] + 1

r2 = r2.merge(r2_tot, how = 'left', on = ['year', 'month', 'address_gu', 'sub_address'])
r2['ratio'] = r2['call_count_x'] / r2['call_count_y']

r2 = r2.pivot(index = ['year', 'month', 'address_gu', 'sub_address'], columns = 'sub_cat', values = 'ratio').reset_index()
r2 = r2.fillna(0)
r2.columns = ['year', 'month', 'address_gu', 'sub_address'] + [f'prev_year_{col}' for col in r2.columns[4: ]]

r2 = r2.rename(columns = {'prev_year_기타': 'prev_year_sub_기타'})

In [183]:
# 병합
r = pd.merge(r1, r2, 'inner', ['year', 'month', 'address_gu', 'sub_address'])

# 날짜 범위
date_range = pd.date_range(start = '2020-05-01', end = '2024-10-31', freq = 'ME')
date_df = pd.DataFrame({
    'year': date_range.year,
    'month': date_range.month
})

# Unique 'address_gu' + 'sub_address' 조합 추출
sub_addrs = r[['address_gu', 'sub_address']].drop_duplicates()
sub_addrs = sub_addrs.sort_values(['address_gu', 'sub_address']).reset_index(drop = True)

# 'year' + 'month' + 'day' + 'address_gu' + 'sub_address' 조합 생성
full_index = date_df.merge(sub_addrs, how = 'cross')
full_index = full_index.loc[full_index['month'].isin(range(5, 11))]

# 빈 날짜 + 지역 조합 채우기
r = full_index.merge(
    r,
    how = 'left',
    on = ['year', 'month', 'address_gu', 'sub_address']
)

# 결측값은 연도에 무관한 월별 중간값으로 대체
cols_to_fill = r.columns.difference(
    ['year', 'month', 'address_gu', 'sub_address']
).to_list()

r[cols_to_fill] = r[cols_to_fill].fillna(
    r.groupby(['month', 'address_gu', 'sub_address'])[cols_to_fill].transform('median')
)

# 그럼에도 불구하고 결측치가 있다면 0.0으로 대체
r.fillna(0, inplace = True)

# 회의 후 필요한 컬럼만 선택: 'sub_cat'에서는 '구급기타'만 선택
r = r.copy()[['year', 'month', 'address_gu', 'sub_address', 'prev_year_구급',
              'prev_year_구조', 'prev_year_기타', 'prev_year_화재', 'prev_year_교통사고',
              'prev_year_구급기타']]

# 저장
r.to_csv('merge9.csv', index = False, encoding = 'cp949')

# 조회
r

,year,month,address_gu,sub_address,prev_year_구급,prev_year_구조,prev_year_기타,prev_year_화재,prev_year_교통사고,prev_year_구급기타
0,2020,5,강서구,강동동,0.522727,0.208333,0.215909,0.0,0.522727,0.0
1,2020,5,강서구,구랑동,0.500000,0.500000,0.000000,0.0,1.000000,0.0
2,2020,5,강서구,녹산동,0.708333,0.166667,0.000000,0.0,0.666667,0.0
3,2020,5,강서구,눌차동,0.750000,0.000000,0.250000,0.0,0.000000,0.5
4,2020,5,강서구,대저1동,0.585714,0.378571,0.098214,0.0,0.535714,0.0
...,...,...,...,...,...,...,...,...,...,...
4045,2024,10,해운대구,송정동,0.583333,0.083333,0.333333,0.0,0.166667,0.0
4046,2024,10,해운대구,우동,0.671233,0.164384,0.164384,0.0,0.287671,0.0
4047,2024,10,해운대구,재송동,0.870968,0.096774,0.032258,0.0,0.322581,0.0
4048,2024,10,해운대구,좌동,0.852941,0.088235,0.058824,0.0,0.264706,0.0
4049,2024,10,해운대구,중동,0.658537,0.195122,0.146341,0.0,0.292683,0.0

# 전처리

In [3]:
# --------------------------------------------------
# Test data를 고려해 input에 자동으로 feature를 추가하는 함수 정의
# --------------------------------------------------
# ! ! ! 입력되는 dataframe은 train 데이터와 같은 dtype과 (prefix를 뗀) 컬럼명을 가져야 함 ! ! !
# --------------------------------------------------
def wowthatisamazing(x):
    out = x.copy()
    
    # -----
    # 날짜를 timestamp로 변환 후 정수 컬럼 'year', 'month', 'day', 'day_of_the_week' 생성
    # -----
    out['tm'] = pd.to_datetime(out['tm'].astype(str), format = '%Y%m%d')

    # 요일
    out['day_of_the_week'] = out['tm'].dt.day_name().astype(object)
    out['year'] = out['tm'].dt.year.astype(int)
    out['month'] = out['tm'].dt.month.astype(int)
    out['day'] = out['tm'].dt.day.astype(int)

    # -----
    # 원본 날짜 컬럼 제거
    # -----
    out = out.drop('tm', axis = 1)

    # -----
    # 기상 자료 dtype 정리
    # -----
    out[[
        'ta_max', 'ta_min', 'ta_max_min', 'hm_min', 
        'hm_max', 'ws_max', 'ws_ins_max', 'rn_day'
    ]] = out[[
        'ta_max', 'ta_min', 'ta_max_min', 'hm_min', 
        'hm_max', 'ws_max', 'ws_ins_max', 'rn_day'
    ]].astype(float)
    out['stn'] = out['stn'].astype(object)

    # -----
    # 면에서 읍으로 승격된 행정 구역 통일 ('merge2.csv'와 'merge9.csv'가 작동하기 위한 조건)
    # -----
    out['sub_address'] = out['sub_address'].replace({'일광면': '일광읍', '정관면': '정관읍'})

    merge0 = pd.read_csv('merge0.csv', encoding = 'cp949')
    merge1 = pd.read_csv('merge1.csv', encoding = 'cp949')
    merge2 = pd.read_csv('merge2.csv', encoding = 'cp949')
    
    merge4 = pd.read_csv('merge4.csv', encoding = 'cp949')
    
    merge6 = pd.read_csv('merge6.csv', encoding = 'cp949', dtype = {'gu_cluster': object})
    merge7 = pd.read_csv('merge7.csv', encoding = 'cp949')
    merge8 = pd.read_csv('merge8.csv', encoding = 'cp949')
    merge9 = pd.read_csv('merge9.csv', encoding = 'cp949')

    out = out.merge(merge0, how = 'left', on = ['year', 'month', 'address_gu'])
    out = out.merge(merge1, how = 'left', on = ['year', 'month', 'address_gu', 'sub_address'])
    out = out.merge(merge2, how = 'left', on = ['year', 'month', 'address_gu'])
    
    out = out.merge(merge4, how = 'left', on = ['year', 'month', 'day', 'address_gu', 'sub_address'])
    
    out = out.merge(merge6, how = 'left', on = ['address_gu'])
    out = out.merge(merge7, how = 'left', on = ['address_gu', 'sub_address'])
    out = out.merge(merge8, how = 'left', on = ['year', 'month', 'address_gu', 'sub_address'])
    out = out.merge(merge9, how = 'left', on = ['year', 'month', 'address_gu', 'sub_address'])

    # -----
    # 날씨 파생 변수
    # -----
    cols_to_fill = [
        'ta_max', 'ta_min', 'ta_max_min', 'hm_min',
        'hm_max', 'ws_max', 'ws_ins_max', 'rn_day'
    ]

    out2 = out.copy()[[
        'year', 'month', 'day', 'address_gu', 'sub_address', 'gu_cluster'
    ] + cols_to_fill]

    # 3단계 rolling 기반 imputation

    # 1차: 같은 날짜 + 같은 구의 과거 10일 평균으로 imputation
    for col in cols_to_fill:
        out2[col] = out2.groupby(['year', 'month', 'day', 'address_gu'])[col].transform(
            lambda s: s.fillna(s.shift(1).rolling(window = 10, min_periods = 1).mean())
        )

    # 2차: 같은 날짜 + 같은 클러스터의 과거 10일 평균으로 imputation
    for col in cols_to_fill:
        out2[col] = out2.groupby(['year', 'month', 'day', 'gu_cluster'])[col].transform(
            lambda s: s.fillna(s.shift(1).rolling(window = 10, min_periods = 1).mean())
        )

    # 3차: 같은 월 + 같은 클러스터의 과거 10일 평균으로 imputation
    for col in cols_to_fill:
        out2[col] = out2.groupby(['month', 'gu_cluster'])[col].transform(
            lambda s: s.fillna(s.shift(1).rolling(window = 10, min_periods = 1).mean())
        )
    
    # 그럼에도 결측치가 있다면 클러스터의 중간값으로 대체
    out2[cols_to_fill] = out2[cols_to_fill].fillna(out2.groupby(['year', 'month', 'day', 'gu_cluster'])[cols_to_fill].transform('median'))

    # 생성한 결측치를 원본에 넣음
    out[cols_to_fill] = out[cols_to_fill].fillna(out2[cols_to_fill])

    # 파생 변수 생성
    out['hm_range'] = out['hm_max'] - out['hm_min']
    out['ta_hm_ratio'] = out['ta_max'] / out['hm_min']
    out['wind_diff'] = out['ws_ins_max'] - out['ws_max']
    out['hot_day'] = (out['ta_max'] > 30).astype(int)
    out['humid_day'] = (out['hm_min'] > 70).astype(int)
    out['windy_day'] = ((out['ws_max'] > 10) | (out['ws_ins_max'] > 15)).astype(int)
    out['rainy_day'] = (out['rn_day'] > 0).astype(int)
    out['heavy_rain_day'] = (out['rn_day'] >= 30).astype(int)

    # 비율 inf를 max로 변경
    out['ta_hm_ratio'] = out['ta_hm_ratio'].replace(
        np.inf,
        out['ta_hm_ratio'][~np.isinf(out['ta_hm_ratio'])].max()
    )

    # 2020-2023의 날짜 + 구별 날씨 데이터 평균 (모든 날씨는 stn을 기준으로 집계되므로, 관측 지점을 섞어 새로운 변수를 만듬. 'sub_address'별로 집계 시 섞이지 않음)
    gu_cols_to_fill = [
        'gu_ta_max', 'gu_ta_min', 'gu_ta_max_min', 'gu_hm_min', 
        'gu_hm_max', 'gu_ws_max', 'gu_ws_ins_max', 'gu_rn_day'
    ]
    out[gu_cols_to_fill] = out.groupby(
        ['year', 'month', 'day', 'address_gu']
    )[cols_to_fill].transform('mean')

    # -----
    # 8월, 9월 여부
    # -----
    out['is_aug_sep'] = (out['month'].isin([8, 9])).astype(int)

    out = out.sort_values(by = ['year', 'month', 'day'], ascending = True, ignore_index = True)
    
    return out

In [4]:
# 변수 추가
df_full = wowthatisamazing(df)

# 출력 변수
y = df_full['call_count']

# 입력 변수
x = df_full.drop(['Unnamed: 0', 'address_city', 'call_count'], axis = 1)

# 컬럼 타입 구분
num_col = x.select_dtypes(include = 'number').columns.to_list()
cat_col = x.select_dtypes(exclude = 'number').columns.to_list()

# 전처리기
preprocessor = ColumnTransformer([
    ('num', 'passthrough', num_col),
    ('cat', TargetEncoder(
        target_type = 'continuous', 
        shuffle = False
    ), cat_col)
]).set_output(transform = 'pandas')

# CV 정의 
cv = TimeSeriesSplit(n_splits = 5)

In [5]:
# Test 데이터
test = pd.read_csv('test_call119.csv', encoding = 'cp949')

# 컬럼명 정리
x_test = test.copy().rename(
    columns = {'TM': 'tm',
               'STN': 'stn'}
)

# Feature 추가
x_test = wowthatisamazing(x_test)

# 불필요한 컬럼 정리
x_test = x_test.drop(['address_city', 'call_count'], axis = 1)

# LGBM

### 모형 선택 (LGBM)

In [7]:
# 모형 파이프라인
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LGBMRegressor(
        objective = 'regression',
        subsample_freq = 1, 
        random_state = 42, 
        verbosity = -1, 
        device = 'gpu'
    ))
])

In [189]:
# Optuna 목적 함수
def objective(trial):
    params = {
        'model__num_leaves': trial.suggest_int('num_leaves', 31, 256),
        'model__max_depth': trial.suggest_int('max_depth', 4, 16),
        'model__learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.2, log = True),
        'model__n_estimators': trial.suggest_int('n_estimators', 300, 2000),
        'model__min_split_gain': trial.suggest_float('min_split_gain', 0.0, 0.1),
        'model__min_child_samples': trial.suggest_int('min_child_samples', 50, 300),
        'model__subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'model__colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'model__reg_alpha': trial.suggest_float('reg_alpha', 0.0, 10.0),
        'model__reg_lambda': trial.suggest_float('reg_lambda', 0.0, 10.0)
    }

    optuna_pipeline = clone(pipeline).set_params(**params)

    scores = cross_validate(
        optuna_pipeline, x, y,
        scoring = 'neg_root_mean_squared_error',
        cv = cv,
        n_jobs = 4,
        verbose = 1
    )
    
    return -scores['test_score'].mean()

# Optuna 실행
os.environ['PYTHONHASHSEED'] = str(42)
sampler = optuna.samplers.TPESampler(seed = 42)
study = optuna.create_study(
    direction = 'minimize',
    study_name = 'predict_call_count',
    sampler = sampler
)
study.optimize(objective, n_trials = 100, n_jobs = 3, show_progress_bar = True)

[I 2025-06-25 17:59:06,371] A new study created in memory with name: predict_call_count

  0%|          | 0/100 [00:00<?, ?it/s]

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  2.0min finished

[I 2025-06-25 18:01:04,915] Trial 0 finished with value: 1.3416410344185516 and parameters: {'num_leaves': 119, 'max_depth': 6, 'learning_rate': 0.0014354408469297998, 'n_estimators': 1061, 'min_split_gain': 0.018953297223907428, 'min_child_samples': 219, 'subsample': 0.9003978850120776, 'colsample_bytree': 0.9569484942933362, 'reg_alpha': 7.626399249017056, 'reg_lambda': 7.137742189953129}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  2.6min finished

[I 2025-06-25 18:01:41,785] Trial 1 finished with value: 1.4406750068648768 and parameters: {'num_leaves': 164, 'max_depth': 12, 'learning_rate': 0.0021758834799356056, 'n_estimators': 1955, 'min_split_gain': 0.08356818056139673, 'min_child_samples': 271, 'subsample': 0.8026782677234883, 'colsample_bytree': 0.9175056280966686, 'reg_alpha': 4.675719155496219, 'reg_lambda': 4.255541510565013}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  2.8min finished

[I 2025-06-25 18:01:57,514] Trial 2 finished with value: 1.6081898088218893 and parameters: {'num_leaves': 47, 'max_depth': 15, 'learning_rate': 0.008418996572663866, 'n_estimators': 1725, 'min_split_gain': 0.05845769866895069, 'min_child_samples': 113, 'subsample': 0.8350311844636433, 'colsample_bytree': 0.8597090978127505, 'reg_alpha': 2.6814415579960613, 'reg_lambda': 2.6069860477849547}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.1min finished

[I 2025-06-25 18:02:11,264] Trial 3 finished with value: 1.8726657622951248 and parameters: {'num_leaves': 32, 'max_depth': 13, 'learning_rate': 0.06626110538261917, 'n_estimators': 1034, 'min_split_gain': 0.04427264103068518, 'min_child_samples': 93, 'subsample': 0.9046116322383865, 'colsample_bytree': 0.7651255760691749, 'reg_alpha': 2.9008982131178063, 'reg_lambda': 3.1080796703586735}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.4min finished

[I 2025-06-25 18:03:07,986] Trial 4 finished with value: 1.6048588318495973 and parameters: {'num_leaves': 220, 'max_depth': 16, 'learning_rate': 0.01191827974255383, 'n_estimators': 979, 'min_split_gain': 0.0511174889749922, 'min_child_samples': 120, 'subsample': 0.9854302683356732, 'colsample_bytree': 0.9946025547424576, 'reg_alpha': 7.257654016793427, 'reg_lambda': 3.0539443166842863}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.3min finished

[I 2025-06-25 18:03:16,370] Trial 5 finished with value: 1.54827891628012 and parameters: {'num_leaves': 210, 'max_depth': 13, 'learning_rate': 0.03102090061285568, 'n_estimators': 481, 'min_split_gain': 0.09216445964150798, 'min_child_samples': 204, 'subsample': 0.6664820798848571, 'colsample_bytree': 0.85492231183858, 'reg_alpha': 9.8395151791015, 'reg_lambda': 7.128326915698798}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.7min finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:03:52,677] Trial 6 finished with value: 1.656852191388078 and parameters: {'num_leaves': 53, 'max_depth': 12, 'learning_rate': 0.03951304127630311, 'n_estimators': 1372, 'min_split_gain': 0.05881622178677375, 'min_child_samples': 208, 'subsample': 0.8871122481336492, 'colsample_bytree': 0.8509117049468775, 'reg_alpha': 0.8407080081318885, 'reg_lambda': 4.467676362848315}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.3min finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:04:26,045] Trial 7 finished with value: 1.3988859463141239 and parameters: {'num_leaves': 51, 'max_depth': 10, 'learning_rate': 0.0024995292777461077, 'n_estimators': 1127, 'min_split_gain': 0.0013199233251142473, 'min_child_samples': 231, 'subsample': 0.9189079477491906, 'colsample_bytree': 0.9676715770001587, 'reg_alpha': 3.6733036659371523, 'reg_lambda': 0.2567497109927297}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.3min finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:04:36,953] Trial 8 finished with value: 1.6772206143052724 and parameters: {'num_leaves': 172, 'max_depth': 9, 'learning_rate': 0.017532833542865316, 'n_estimators': 787, 'min_split_gain': 0.026330202283472427, 'min_child_samples': 100, 'subsample': 0.8651184312275544, 'colsample_bytree': 0.5623859038480423, 'reg_alpha': 3.3975254959544046, 'reg_lambda': 8.121611179745763}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.1min finished

[I 2025-06-25 18:04:58,154] Trial 9 finished with value: 1.5993751815297443 and parameters: {'num_leaves': 236, 'max_depth': 8, 'learning_rate': 0.011539158714493299, 'n_estimators': 1378, 'min_split_gain': 0.025462843140829295, 'min_child_samples': 249, 'subsample': 0.6412013660625199, 'colsample_bytree': 0.5889146128992029, 'reg_alpha': 3.971188574989365, 'reg_lambda': 6.703420996496167}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.8min finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:06:25,093] Trial 11 finished with value: 1.7428625005302885 and parameters: {'num_leaves': 167, 'max_depth': 5, 'learning_rate': 0.048182419214078884, 'n_estimators': 1866, 'min_split_gain': 0.010993268919882927, 'min_child_samples': 154, 'subsample': 0.6130329139572578, 'colsample_bytree': 0.8620553951404515, 'reg_alpha': 7.324139778882367, 'reg_lambda': 6.437897786914869}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.4min finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:06:25,400] Trial 12 finished with value: 1.3829047441380244 and parameters: {'num_leaves': 101, 'max_depth': 5, 'learning_rate': 0.0010174452056731789, 'n_estimators': 410, 'min_split_gain': 0.0010537008120858338, 'min_child_samples': 300, 'subsample': 0.7306485652085652, 'colsample_bytree': 0.6736031533412791, 'reg_alpha': 7.148015955163453, 'reg_lambda': 9.809738170809489}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  2.3min finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:06:41,815] Trial 10 finished with value: 1.4340452156133416 and parameters: {'num_leaves': 187, 'max_depth': 13, 'learning_rate': 0.002453003442523163, 'n_estimators': 1520, 'min_split_gain': 0.06106742394233258, 'min_child_samples': 100, 'subsample': 0.7847273719178107, 'colsample_bytree': 0.9394959674752623, 'reg_alpha': 2.3631198142124097, 'reg_lambda': 0.5460322021951336}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   18.4s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:06:44,083] Trial 14 finished with value: 1.3895900911071084 and parameters: {'num_leaves': 105, 'max_depth': 4, 'learning_rate': 0.001063802010639273, 'n_estimators': 308, 'min_split_gain': 0.020548303512660696, 'min_child_samples': 293, 'subsample': 0.7272210952862799, 'colsample_bytree': 0.6768884702540563, 'reg_alpha': 6.9291064196264305, 'reg_lambda': 9.43790277094957}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   22.0s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:06:47,380] Trial 13 finished with value: 1.35152753470724 and parameters: {'num_leaves': 97, 'max_depth': 5, 'learning_rate': 0.0011904287688736818, 'n_estimators': 1343, 'min_split_gain': 0.004109001329469328, 'min_child_samples': 299, 'subsample': 0.9802368475451554, 'colsample_bytree': 0.9918350463877907, 'reg_alpha': 6.652184002832205, 'reg_lambda': 0.05587994875100524}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:    7.1s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:06:49,224] Trial 15 finished with value: 1.3843477072573158 and parameters: {'num_leaves': 108, 'max_depth': 4, 'learning_rate': 0.001066387188787346, 'n_estimators': 399, 'min_split_gain': 0.01662214726967408, 'min_child_samples': 299, 'subsample': 0.7295703544944057, 'colsample_bytree': 0.6659315623768716, 'reg_alpha': 6.778020546631833, 'reg_lambda': 9.715544228637949}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   15.7s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:07:00,069] Trial 16 finished with value: 1.8313524179463425 and parameters: {'num_leaves': 113, 'max_depth': 6, 'learning_rate': 0.16697170561343747, 'n_estimators': 685, 'min_split_gain': 0.0005379398965446591, 'min_child_samples': 162, 'subsample': 0.725804905458209, 'colsample_bytree': 0.6989180902947435, 'reg_alpha': 9.23893687488573, 'reg_lambda': 9.936748508459337}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   25.4s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:07:13,086] Trial 17 finished with value: 1.396490088396994 and parameters: {'num_leaves': 108, 'max_depth': 7, 'learning_rate': 0.00452436405411317, 'n_estimators': 740, 'min_split_gain': 0.03891671467073686, 'min_child_samples': 157, 'subsample': 0.99837769581991, 'colsample_bytree': 0.7808786856702605, 'reg_alpha': 9.103083216912985, 'reg_lambda': 5.898322155721564}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   35.6s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:07:25,023] Trial 18 finished with value: 1.843116222258318 and parameters: {'num_leaves': 137, 'max_depth': 7, 'learning_rate': 0.16528990568385565, 'n_estimators': 795, 'min_split_gain': 0.03936102638101142, 'min_child_samples': 168, 'subsample': 0.9916480944219579, 'colsample_bytree': 0.7742835855630167, 'reg_alpha': 9.730998496472903, 'reg_lambda': 5.688166209505789}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   50.0s finished

[I 2025-06-25 18:07:50,378] Trial 19 finished with value: 1.684862754007618 and parameters: {'num_leaves': 136, 'max_depth': 7, 'learning_rate': 0.005828266184802873, 'n_estimators': 1318, 'min_split_gain': 0.0366657674330943, 'min_child_samples': 52, 'subsample': 0.9852969577366324, 'colsample_bytree': 0.788037346151574, 'reg_alpha': 5.58489880258567, 'reg_lambda': 1.6123498554650695}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   54.3s finished

[I 2025-06-25 18:08:07,895] Trial 20 finished with value: 1.4628061484897845 and parameters: {'num_leaves': 137, 'max_depth': 7, 'learning_rate': 0.004758528393762037, 'n_estimators': 1302, 'min_split_gain': 0.02843348520204781, 'min_child_samples': 251, 'subsample': 0.9496868452849767, 'colsample_bytree': 0.5017302826776543, 'reg_alpha': 5.785713968572589, 'reg_lambda': 1.7028333777947702}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   56.1s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:08:21,427] Trial 21 finished with value: 1.4324465830984734 and parameters: {'num_leaves': 84, 'max_depth': 6, 'learning_rate': 0.004465169649322057, 'n_estimators': 1359, 'min_split_gain': 0.03186750568859128, 'min_child_samples': 252, 'subsample': 0.9414988970864003, 'colsample_bytree': 0.9194780660136889, 'reg_alpha': 5.995663141668504, 'reg_lambda': 1.25936633082401}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.2min finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:09:03,199] Trial 22 finished with value: 1.4261801961756002 and parameters: {'num_leaves': 79, 'max_depth': 9, 'learning_rate': 0.0034366974006445916, 'n_estimators': 1610, 'min_split_gain': 0.012802981785055676, 'min_child_samples': 256, 'subsample': 0.9386711004869237, 'colsample_bytree': 0.9170651634998902, 'reg_alpha': 8.306885342392789, 'reg_lambda': 8.000963320425347}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.1min finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:09:12,406] Trial 23 finished with value: 1.3841317816279803 and parameters: {'num_leaves': 81, 'max_depth': 5, 'learning_rate': 0.0014799897818095471, 'n_estimators': 1673, 'min_split_gain': 0.008658105976211684, 'min_child_samples': 282, 'subsample': 0.9434019074744497, 'colsample_bytree': 0.9161279808973819, 'reg_alpha': 8.285131723417255, 'reg_lambda': 8.442254257735625}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.1min finished

[I 2025-06-25 18:09:26,758] Trial 24 finished with value: 1.4194675568665205 and parameters: {'num_leaves': 85, 'max_depth': 5, 'learning_rate': 0.0016208295278545665, 'n_estimators': 1658, 'min_split_gain': 0.009307462082707125, 'min_child_samples': 278, 'subsample': 0.7863384810381925, 'colsample_bytree': 0.6225107273454905, 'reg_alpha': 8.060382291766064, 'reg_lambda': 8.317082405765808}. Best is trial 0 with value: 1.3416410344185516.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   25.9s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:09:29,375] Trial 25 finished with value: 1.333054930825266 and parameters: {'num_leaves': 92, 'max_depth': 5, 'learning_rate': 0.0015637273256621515, 'n_estimators': 550, 'min_split_gain': 0.006263196618742366, 'min_child_samples': 212, 'subsample': 0.7697676417949492, 'colsample_bytree': 0.6334619541993216, 'reg_alpha': 8.561069643218248, 'reg_lambda': 8.699235417973721}. Best is trial 25 with value: 1.333054930825266.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   26.9s finished

[I 2025-06-25 18:09:39,591] Trial 26 finished with value: 1.3611505534158246 and parameters: {'num_leaves': 122, 'max_depth': 5, 'learning_rate': 0.00197979885321698, 'n_estimators': 973, 'min_split_gain': 0.00591415719235921, 'min_child_samples': 207, 'subsample': 0.7790709093008336, 'colsample_bytree': 0.6156242669810481, 'reg_alpha': 8.172819988232972, 'reg_lambda': 7.648744623767457}. Best is trial 25 with value: 1.333054930825266.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   15.2s finished

[I 2025-06-25 18:09:42,287] Trial 27 finished with value: 1.3339838480760666 and parameters: {'num_leaves': 118, 'max_depth': 4, 'learning_rate': 0.0010521166643587, 'n_estimators': 615, 'min_split_gain': 0.0012050995892971634, 'min_child_samples': 207, 'subsample': 0.8500490979021682, 'colsample_bytree': 0.7237493704096613, 'reg_alpha': 6.302105673354797, 'reg_lambda': 7.448534475191283}. Best is trial 25 with value: 1.333054930825266.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   20.7s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:09:50,346] Trial 28 finished with value: 1.3582560892599387 and parameters: {'num_leaves': 124, 'max_depth': 4, 'learning_rate': 0.0016943781618751496, 'n_estimators': 1015, 'min_split_gain': 0.021621965190400036, 'min_child_samples': 213, 'subsample': 0.8257038129428219, 'colsample_bytree': 0.9941708457390167, 'reg_alpha': 6.2859027482676, 'reg_lambda': 7.13577999625509}. Best is trial 25 with value: 1.333054930825266.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   14.1s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:09:54,014] Trial 29 finished with value: 1.3458451634160387 and parameters: {'num_leaves': 70, 'max_depth': 4, 'learning_rate': 0.0030581076640546407, 'n_estimators': 571, 'min_split_gain': 0.01763040549459945, 'min_child_samples': 186, 'subsample': 0.8164569025694034, 'colsample_bytree': 0.7271458382436078, 'reg_alpha': 5.001756439899832, 'reg_lambda': 8.706680759100252}. Best is trial 25 with value: 1.333054930825266.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   15.6s finished

[I 2025-06-25 18:09:58,379] Trial 30 finished with value: 1.3561121966814191 and parameters: {'num_leaves': 151, 'max_depth': 4, 'learning_rate': 0.003072584383534665, 'n_estimators': 626, 'min_split_gain': 0.019383707410446784, 'min_child_samples': 228, 'subsample': 0.8428118043678398, 'colsample_bytree': 0.7399035589706827, 'reg_alpha': 4.8452928292069135, 'reg_lambda': 9.000445180926178}. Best is trial 25 with value: 1.333054930825266.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   31.5s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:10:22,096] Trial 31 finished with value: 1.348304135839852 and parameters: {'num_leaves': 147, 'max_depth': 10, 'learning_rate': 0.0027847573449577313, 'n_estimators': 591, 'min_split_gain': 0.0713463020819052, 'min_child_samples': 195, 'subsample': 0.8596007060474008, 'colsample_bytree': 0.7240294436985474, 'reg_alpha': 5.484722143085259, 'reg_lambda': 9.169613600449942}. Best is trial 25 with value: 1.333054930825266.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   42.4s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:10:36,655] Trial 32 finished with value: 1.4317306774889267 and parameters: {'num_leaves': 156, 'max_depth': 10, 'learning_rate': 0.00817104977965595, 'n_estimators': 570, 'min_split_gain': 0.0716676830030734, 'min_child_samples': 231, 'subsample': 0.8670796565883621, 'colsample_bytree': 0.7279309316457971, 'reg_alpha': 4.938654077855335, 'reg_lambda': 5.200515479684011}. Best is trial 25 with value: 1.333054930825266.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   40.8s finished

[I 2025-06-25 18:10:39,653] Trial 33 finished with value: 1.3289758621092322 and parameters: {'num_leaves': 66, 'max_depth': 6, 'learning_rate': 0.0021135658640388825, 'n_estimators': 544, 'min_split_gain': 0.07241089075872326, 'min_child_samples': 187, 'subsample': 0.8092195358668587, 'colsample_bytree': 0.7246782745148297, 'reg_alpha': 5.179663293794905, 'reg_lambda': 8.762278040514975}. Best is trial 33 with value: 1.3289758621092322.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   30.2s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:10:52,585] Trial 34 finished with value: 1.337128634114792 and parameters: {'num_leaves': 80, 'max_depth': 6, 'learning_rate': 0.001682233808107414, 'n_estimators': 864, 'min_split_gain': 0.01559076706166624, 'min_child_samples': 188, 'subsample': 0.8170193535651104, 'colsample_bytree': 0.8214831038136242, 'reg_alpha': 4.625531569204916, 'reg_lambda': 8.674796770512232}. Best is trial 33 with value: 1.3289758621092322.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   22.6s finished

[I 2025-06-25 18:10:59,581] Trial 35 finished with value: 1.3254453900560412 and parameters: {'num_leaves': 65, 'max_depth': 6, 'learning_rate': 0.001514487195106718, 'n_estimators': 495, 'min_split_gain': 0.013896891904715516, 'min_child_samples': 186, 'subsample': 0.8122784930840637, 'colsample_bytree': 0.8178583512947661, 'reg_alpha': 4.230808131405039, 'reg_lambda': 8.688050851113951}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   31.8s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:11:11,787] Trial 36 finished with value: 1.3413703788841218 and parameters: {'num_leaves': 59, 'max_depth': 6, 'learning_rate': 0.0014215989344315112, 'n_estimators': 900, 'min_split_gain': 0.09876385201350082, 'min_child_samples': 137, 'subsample': 0.7527674889481516, 'colsample_bytree': 0.818050055382022, 'reg_alpha': 7.690109500763175, 'reg_lambda': 7.501864729982575}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   30.0s finished

[I 2025-06-25 18:11:23,065] Trial 37 finished with value: 1.3577940882399122 and parameters: {'num_leaves': 65, 'max_depth': 6, 'learning_rate': 0.0018948101163323865, 'n_estimators': 864, 'min_split_gain': 0.07681602304106054, 'min_child_samples': 138, 'subsample': 0.7636511002862938, 'colsample_bytree': 0.6515003613836022, 'reg_alpha': 4.066275424332034, 'reg_lambda': 7.565552817222203}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   35.2s finished

[I 2025-06-25 18:11:35,272] Trial 38 finished with value: 1.3352536292583563 and parameters: {'num_leaves': 64, 'max_depth': 8, 'learning_rate': 0.0019887824224430277, 'n_estimators': 481, 'min_split_gain': 0.09884183554132957, 'min_child_samples': 141, 'subsample': 0.7578715052118772, 'colsample_bytree': 0.8156405582990722, 'reg_alpha': 4.122851929198504, 'reg_lambda': 7.801991598923781}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   34.3s finished

[I 2025-06-25 18:11:46,564] Trial 39 finished with value: 1.3323135836102167 and parameters: {'num_leaves': 38, 'max_depth': 8, 'learning_rate': 0.0019137513111769351, 'n_estimators': 493, 'min_split_gain': 0.08648484357779979, 'min_child_samples': 184, 'subsample': 0.6931464466365875, 'colsample_bytree': 0.6351641799977058, 'reg_alpha': 4.14261087074528, 'reg_lambda': 7.886608242528481}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   30.1s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:11:53,471] Trial 40 finished with value: 1.480513041261925 and parameters: {'num_leaves': 34, 'max_depth': 8, 'learning_rate': 0.02010180510931037, 'n_estimators': 479, 'min_split_gain': 0.05327800310492228, 'min_child_samples': 180, 'subsample': 0.7034669557694555, 'colsample_bytree': 0.8097185237443889, 'reg_alpha': 1.84209644300865, 'reg_lambda': 6.362371348751637}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   25.1s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:12:00,697] Trial 41 finished with value: 1.373206964933783 and parameters: {'num_leaves': 37, 'max_depth': 8, 'learning_rate': 0.006131507268691726, 'n_estimators': 333, 'min_split_gain': 0.05333460386594281, 'min_child_samples': 180, 'subsample': 0.6761412454319353, 'colsample_bytree': 0.6967524247125823, 'reg_alpha': 2.8824896000787747, 'reg_lambda': 9.137337215671497}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   22.3s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:12:09,119] Trial 42 finished with value: 1.3882564025274475 and parameters: {'num_leaves': 38, 'max_depth': 9, 'learning_rate': 0.007051825305479084, 'n_estimators': 306, 'min_split_gain': 0.08543427079936228, 'min_child_samples': 177, 'subsample': 0.6927116200807125, 'colsample_bytree': 0.5131488407481346, 'reg_alpha': 2.1626747470479244, 'reg_lambda': 4.103148505670613}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   23.7s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:12:17,438] Trial 43 finished with value: 1.3513933420082502 and parameters: {'num_leaves': 35, 'max_depth': 9, 'learning_rate': 0.0013375997630057012, 'n_estimators': 324, 'min_split_gain': 0.08334879465238816, 'min_child_samples': 195, 'subsample': 0.6785584434117653, 'colsample_bytree': 0.5534215283611787, 'reg_alpha': 2.5370849956259636, 'reg_lambda': 9.173848810244149}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   36.5s finished

[I 2025-06-25 18:12:37,518] Trial 44 finished with value: 1.3321959748207832 and parameters: {'num_leaves': 44, 'max_depth': 9, 'learning_rate': 0.0014166287358857118, 'n_estimators': 674, 'min_split_gain': 0.08678914194157128, 'min_child_samples': 197, 'subsample': 0.800903526424331, 'colsample_bytree': 0.555283064713099, 'reg_alpha': 4.316995445488818, 'reg_lambda': 4.054492315410423}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   39.9s finished

[I 2025-06-25 18:12:49,452] Trial 45 finished with value: 1.3536119444649093 and parameters: {'num_leaves': 44, 'max_depth': 7, 'learning_rate': 0.002303400541977996, 'n_estimators': 694, 'min_split_gain': 0.09210771217306245, 'min_child_samples': 224, 'subsample': 0.8058971736529141, 'colsample_bytree': 0.6339220397264079, 'reg_alpha': 3.3065440363245115, 'reg_lambda': 6.837444140898331}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   43.1s finished

[I 2025-06-25 18:13:01,042] Trial 46 finished with value: 1.3569489593451365 and parameters: {'num_leaves': 49, 'max_depth': 7, 'learning_rate': 0.0024647147355444693, 'n_estimators': 691, 'min_split_gain': 0.08894141097626948, 'min_child_samples': 219, 'subsample': 0.8023055728758812, 'colsample_bytree': 0.6281644575314385, 'reg_alpha': 3.3178098437682655, 'reg_lambda': 6.9702761570053715}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   47.6s finished

[I 2025-06-25 18:13:25,570] Trial 47 finished with value: 1.358214050491223 and parameters: {'num_leaves': 49, 'max_depth': 11, 'learning_rate': 0.0023110674485468784, 'n_estimators': 700, 'min_split_gain': 0.08919746848304327, 'min_child_samples': 224, 'subsample': 0.801983452530086, 'colsample_bytree': 0.548227197193651, 'reg_alpha': 3.355590370331975, 'reg_lambda': 4.178241014980694}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   51.5s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:13:41,247] Trial 48 finished with value: 1.3771893553859726 and parameters: {'num_leaves': 54, 'max_depth': 10, 'learning_rate': 0.003758482633754934, 'n_estimators': 485, 'min_split_gain': 0.06657604260204016, 'min_child_samples': 217, 'subsample': 0.644020144032634, 'colsample_bytree': 0.5804225605061322, 'reg_alpha': 0.5643021909158934, 'reg_lambda': 3.7276854279268843}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   58.6s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:13:59,896] Trial 49 finished with value: 1.373906707378164 and parameters: {'num_leaves': 58, 'max_depth': 11, 'learning_rate': 0.004076889146705927, 'n_estimators': 492, 'min_split_gain': 0.06674182670037368, 'min_child_samples': 197, 'subsample': 0.6474361957531185, 'colsample_bytree': 0.5881256837792114, 'reg_alpha': 0.7380010671497743, 'reg_lambda': 3.711701278596315}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.1min finished

[I 2025-06-25 18:14:30,096] Trial 50 finished with value: 1.3622614998653302 and parameters: {'num_leaves': 94, 'max_depth': 16, 'learning_rate': 0.003518247537828587, 'n_estimators': 490, 'min_split_gain': 0.06634485853526507, 'min_child_samples': 168, 'subsample': 0.8873877333699266, 'colsample_bytree': 0.5873723575106832, 'reg_alpha': 5.2905751853255225, 'reg_lambda': 8.140787289566116}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   54.8s finished

[I 2025-06-25 18:14:36,316] Trial 51 finished with value: 1.462712227119245 and parameters: {'num_leaves': 72, 'max_depth': 14, 'learning_rate': 0.01123748165047521, 'n_estimators': 425, 'min_split_gain': 0.08081720426246196, 'min_child_samples': 197, 'subsample': 0.775119891967894, 'colsample_bytree': 0.5945207360465786, 'reg_alpha': 1.4183844127542988, 'reg_lambda': 3.131122505059044}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.2min finished

[I 2025-06-25 18:15:11,498] Trial 52 finished with value: 1.882270889697321 and parameters: {'num_leaves': 94, 'max_depth': 14, 'learning_rate': 0.10324379434982137, 'n_estimators': 1117, 'min_split_gain': 0.07994841473774603, 'min_child_samples': 241, 'subsample': 0.8984046481902103, 'colsample_bytree': 0.6940106173706275, 'reg_alpha': 0.016060876955964254, 'reg_lambda': 4.843871426752112}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   58.2s finished

[I 2025-06-25 18:15:28,804] Trial 53 finished with value: 1.3402873777477389 and parameters: {'num_leaves': 70, 'max_depth': 15, 'learning_rate': 0.0012648320052069395, 'n_estimators': 400, 'min_split_gain': 0.07853236741977021, 'min_child_samples': 202, 'subsample': 0.8440267965535811, 'colsample_bytree': 0.5329976429498013, 'reg_alpha': 4.40091221652172, 'reg_lambda': 8.771242203446771}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   55.4s finished

[I 2025-06-25 18:15:32,238] Trial 54 finished with value: 1.33511616306962 and parameters: {'num_leaves': 92, 'max_depth': 6, 'learning_rate': 0.0011952325272429373, 'n_estimators': 627, 'min_split_gain': 0.045085795119786984, 'min_child_samples': 239, 'subsample': 0.8339568860983398, 'colsample_bytree': 0.7589949514010488, 'reg_alpha': 4.032771263871657, 'reg_lambda': 4.723489713617952}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   30.7s finished

[I 2025-06-25 18:15:42,711] Trial 55 finished with value: 1.3292080128118229 and parameters: {'num_leaves': 71, 'max_depth': 6, 'learning_rate': 0.001142767686496998, 'n_estimators': 790, 'min_split_gain': 0.005449148943911401, 'min_child_samples': 209, 'subsample': 0.8458673424478643, 'colsample_bytree': 0.7475820510903379, 'reg_alpha': 4.439322773553061, 'reg_lambda': 9.515943396626945}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   22.2s finished

[I 2025-06-25 18:15:51,501] Trial 56 finished with value: 1.3363730040931814 and parameters: {'num_leaves': 91, 'max_depth': 6, 'learning_rate': 0.0010058659507669752, 'n_estimators': 619, 'min_split_gain': 0.047268785736143334, 'min_child_samples': 150, 'subsample': 0.8336400278559302, 'colsample_bytree': 0.6556843463142732, 'reg_alpha': 6.250054096172906, 'reg_lambda': 9.494615752878182}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   26.5s finished

[I 2025-06-25 18:15:59,012] Trial 57 finished with value: 1.33199985456196 and parameters: {'num_leaves': 182, 'max_depth': 5, 'learning_rate': 0.0011735799531740064, 'n_estimators': 783, 'min_split_gain': 0.09503244133268908, 'min_child_samples': 167, 'subsample': 0.8575589012027737, 'colsample_bytree': 0.8729749545429115, 'reg_alpha': 3.6794536782044447, 'reg_lambda': 9.64672191679028}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   38.0s finished

[I 2025-06-25 18:16:21,161] Trial 58 finished with value: 1.3336938868217123 and parameters: {'num_leaves': 44, 'max_depth': 8, 'learning_rate': 0.0014401286722434002, 'n_estimators': 764, 'min_split_gain': 0.005500641298039631, 'min_child_samples': 151, 'subsample': 0.7444600934598586, 'colsample_bytree': 0.8684686299331528, 'reg_alpha': 3.604646939891984, 'reg_lambda': 9.762722467806025}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   46.1s finished

[I 2025-06-25 18:16:38,104] Trial 59 finished with value: 1.3390267148967754 and parameters: {'num_leaves': 44, 'max_depth': 8, 'learning_rate': 0.0014492864590208087, 'n_estimators': 782, 'min_split_gain': 0.07460596708659606, 'min_child_samples': 168, 'subsample': 0.6174228490420385, 'colsample_bytree': 0.8875088130687191, 'reg_alpha': 3.709687060769733, 'reg_lambda': 9.939369125423681}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   59.1s finished

[I 2025-06-25 18:16:58,640] Trial 60 finished with value: 1.3376715624152822 and parameters: {'num_leaves': 188, 'max_depth': 8, 'learning_rate': 0.0019285661130207415, 'n_estimators': 780, 'min_split_gain': 0.09547529069817683, 'min_child_samples': 123, 'subsample': 0.8757294595871812, 'colsample_bytree': 0.8608618372978267, 'reg_alpha': 4.317642573691845, 'reg_lambda': 9.991012618178797}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   54.9s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:17:16,374] Trial 61 finished with value: 1.3509281381434461 and parameters: {'num_leaves': 203, 'max_depth': 7, 'learning_rate': 0.0020122154605283897, 'n_estimators': 929, 'min_split_gain': 0.09409020225273007, 'min_child_samples': 122, 'subsample': 0.7902472016248051, 'colsample_bytree': 0.8756399822672127, 'reg_alpha': 4.339944622233952, 'reg_lambda': 9.624179910036746}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   44.9s finished

[I 2025-06-25 18:17:44,007] Trial 63 finished with value: 1.3286806734216203 and parameters: {'num_leaves': 216, 'max_depth': 5, 'learning_rate': 0.0012243272071601498, 'n_estimators': 532, 'min_split_gain': 0.08672231810885495, 'min_child_samples': 187, 'subsample': 0.7873507679172782, 'colsample_bytree': 0.7841097424081406, 'reg_alpha': 4.611037849294416, 'reg_lambda': 9.552996058312214}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.1min finished

[I 2025-06-25 18:17:47,209] Trial 62 finished with value: 1.349294649628034 and parameters: {'num_leaves': 189, 'max_depth': 9, 'learning_rate': 0.0019112695571314956, 'n_estimators': 935, 'min_split_gain': 0.09459511257519577, 'min_child_samples': 116, 'subsample': 0.8706198716920973, 'colsample_bytree': 0.7931817521480965, 'reg_alpha': 4.485935246882903, 'reg_lambda': 9.511364674548014}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   35.0s finished

[I 2025-06-25 18:17:51,828] Trial 64 finished with value: 1.3255813529695772 and parameters: {'num_leaves': 217, 'max_depth': 5, 'learning_rate': 0.0016943845316512974, 'n_estimators': 543, 'min_split_gain': 0.0860854504324336, 'min_child_samples': 186, 'subsample': 0.8194324888642472, 'colsample_bytree': 0.7896685720152614, 'reg_alpha': 3.728471899124019, 'reg_lambda': 8.448247547628146}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   12.5s finished

[I 2025-06-25 18:17:56,800] Trial 65 finished with value: 1.3361889430620033 and parameters: {'num_leaves': 251, 'max_depth': 5, 'learning_rate': 0.0011084213369656779, 'n_estimators': 522, 'min_split_gain': 0.08488181588156044, 'min_child_samples': 187, 'subsample': 0.9194554294384787, 'colsample_bytree': 0.7965516689877089, 'reg_alpha': 5.2816040920272815, 'reg_lambda': 9.398589750125875}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   14.4s finished

[I 2025-06-25 18:18:02,070] Trial 66 finished with value: 1.3279832105773781 and parameters: {'num_leaves': 218, 'max_depth': 5, 'learning_rate': 0.0012443952506671495, 'n_estimators': 537, 'min_split_gain': 0.08819053782116552, 'min_child_samples': 185, 'subsample': 0.8133431711371634, 'colsample_bytree': 0.7658993069839358, 'reg_alpha': 5.191189377512607, 'reg_lambda': 8.446172324299889}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   19.3s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:18:11,431] Trial 67 finished with value: 1.326733798604047 and parameters: {'num_leaves': 245, 'max_depth': 5, 'learning_rate': 0.0011462513049076393, 'n_estimators': 847, 'min_split_gain': 0.08952408019736484, 'min_child_samples': 172, 'subsample': 0.8197612243718752, 'colsample_bytree': 0.8447558644780659, 'reg_alpha': 5.203948028140619, 'reg_lambda': 8.260950666941977}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   22.5s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:18:19,643] Trial 68 finished with value: 1.3283308985353972 and parameters: {'num_leaves': 217, 'max_depth': 5, 'learning_rate': 0.0012914629475168221, 'n_estimators': 822, 'min_split_gain': 0.08807766414009202, 'min_child_samples': 169, 'subsample': 0.8228499854620354, 'colsample_bytree': 0.8394077206497179, 'reg_alpha': 5.146268382720152, 'reg_lambda': 8.383278365943527}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   21.7s finished

[I 2025-06-25 18:18:24,087] Trial 69 finished with value: 1.3381581818494113 and parameters: {'num_leaves': 222, 'max_depth': 5, 'learning_rate': 0.0012198343724125712, 'n_estimators': 424, 'min_split_gain': 0.09248821849457806, 'min_child_samples': 172, 'subsample': 0.817539412677551, 'colsample_bytree': 0.7606690654110009, 'reg_alpha': 5.123590129972943, 'reg_lambda': 8.359614260019946}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   16.3s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:18:28,016] Trial 70 finished with value: 1.3263371247409297 and parameters: {'num_leaves': 232, 'max_depth': 5, 'learning_rate': 0.002781119683967039, 'n_estimators': 372, 'min_split_gain': 0.09075634432798645, 'min_child_samples': 173, 'subsample': 0.816907720858237, 'colsample_bytree': 0.8475662870791595, 'reg_alpha': 5.9683704915455955, 'reg_lambda': 8.258096340683979}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   10.7s finished

[I 2025-06-25 18:18:30,661] Trial 71 finished with value: 1.3342801257294135 and parameters: {'num_leaves': 227, 'max_depth': 4, 'learning_rate': 0.0028294070349043996, 'n_estimators': 381, 'min_split_gain': 0.09008709081242566, 'min_child_samples': 160, 'subsample': 0.8216430278443131, 'colsample_bytree': 0.841957471458236, 'reg_alpha': 5.757246771287329, 'reg_lambda': 8.349675073234879}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:    8.9s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:18:33,320] Trial 72 finished with value: 1.3308251206649055 and parameters: {'num_leaves': 231, 'max_depth': 4, 'learning_rate': 0.0027970366591760307, 'n_estimators': 364, 'min_split_gain': 0.0822993774620431, 'min_child_samples': 158, 'subsample': 0.7867920811694618, 'colsample_bytree': 0.8397959485798145, 'reg_alpha': 5.856780212922366, 'reg_lambda': 8.49663501180711}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   16.9s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:18:45,091] Trial 73 finished with value: 1.3595870649369055 and parameters: {'num_leaves': 232, 'max_depth': 4, 'learning_rate': 0.0016819615735565998, 'n_estimators': 1236, 'min_split_gain': 0.08882156058171178, 'min_child_samples': 175, 'subsample': 0.7865547980452793, 'colsample_bytree': 0.8434004519048113, 'reg_alpha': 5.767747369264094, 'reg_lambda': 8.46831355760952}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   14.8s finished

[I 2025-06-25 18:18:45,967] Trial 74 finished with value: 1.3315752038100448 and parameters: {'num_leaves': 242, 'max_depth': 4, 'learning_rate': 0.0016637570860255748, 'n_estimators': 441, 'min_split_gain': 0.08150149504240882, 'min_child_samples': 175, 'subsample': 0.7900846920635721, 'colsample_bytree': 0.8350528145651734, 'reg_alpha': 4.8070918842012595, 'reg_lambda': 8.921071363579802}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   22.5s finished

[I 2025-06-25 18:19:07,921] Trial 76 finished with value: 1.3264201167606264 and parameters: {'num_leaves': 244, 'max_depth': 5, 'learning_rate': 0.0016358024349718621, 'n_estimators': 438, 'min_split_gain': 0.07544813897632893, 'min_child_samples': 191, 'subsample': 0.8253223459020825, 'colsample_bytree': 0.8947234077045654, 'reg_alpha': 4.74766222544021, 'reg_lambda': 7.995355039930279}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   37.7s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:19:11,285] Trial 75 finished with value: 1.4269392889205552 and parameters: {'num_leaves': 245, 'max_depth': 5, 'learning_rate': 0.0016880723270360893, 'n_estimators': 1973, 'min_split_gain': 0.07513551512923858, 'min_child_samples': 146, 'subsample': 0.810918382136102, 'colsample_bytree': 0.7707288653344998, 'reg_alpha': 4.7716201434556815, 'reg_lambda': 8.123626332833211}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   27.8s finished

[I 2025-06-25 18:19:14,097] Trial 77 finished with value: 1.5902147056581988 and parameters: {'num_leaves': 213, 'max_depth': 5, 'learning_rate': 0.0328083665368742, 'n_estimators': 545, 'min_split_gain': 0.09982531546825285, 'min_child_samples': 146, 'subsample': 0.8318309604125079, 'colsample_bytree': 0.7766801538839375, 'reg_alpha': 6.600768675967135, 'reg_lambda': 7.343806892359938}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   16.8s finished

[I 2025-06-25 18:19:25,209] Trial 78 finished with value: 1.6243326509400446 and parameters: {'num_leaves': 215, 'max_depth': 5, 'learning_rate': 0.026357722578430783, 'n_estimators': 1066, 'min_split_gain': 0.07708808945439771, 'min_child_samples': 144, 'subsample': 0.8334738622193063, 'colsample_bytree': 0.9050832276762149, 'reg_alpha': 5.415671620149665, 'reg_lambda': 7.264384049424479}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   15.1s finished

[I 2025-06-25 18:19:26,843] Trial 79 finished with value: 1.5489349959646859 and parameters: {'num_leaves': 206, 'max_depth': 5, 'learning_rate': 0.025949048346834255, 'n_estimators': 531, 'min_split_gain': 0.0985681579335065, 'min_child_samples': 162, 'subsample': 0.8262092945158388, 'colsample_bytree': 0.9450107589671941, 'reg_alpha': 6.191398514349673, 'reg_lambda': 7.269805405556416}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   27.0s finished

[I 2025-06-25 18:19:41,605] Trial 80 finished with value: 1.3310098976790052 and parameters: {'num_leaves': 208, 'max_depth': 5, 'learning_rate': 0.0012437623619396944, 'n_estimators': 1069, 'min_split_gain': 0.09714116659521405, 'min_child_samples': 190, 'subsample': 0.8237436211895758, 'colsample_bytree': 0.8846506529838496, 'reg_alpha': 5.507492132085546, 'reg_lambda': 7.816089614965785}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   34.1s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:19:59,622] Trial 81 finished with value: 1.3541982929528689 and parameters: {'num_leaves': 202, 'max_depth': 5, 'learning_rate': 0.0010159660534537153, 'n_estimators': 1871, 'min_split_gain': 0.09705484641435075, 'min_child_samples': 190, 'subsample': 0.853896439180459, 'colsample_bytree': 0.8050120028738892, 'reg_alpha': 6.073640547167628, 'reg_lambda': 6.521310633671975}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   56.5s finished

[I 2025-06-25 18:20:23,678] Trial 82 finished with value: 1.3801248677940696 and parameters: {'num_leaves': 239, 'max_depth': 6, 'learning_rate': 0.0013224891428117928, 'n_estimators': 1890, 'min_split_gain': 0.09145106485428539, 'min_child_samples': 190, 'subsample': 0.8561005779338859, 'colsample_bytree': 0.8307194635983424, 'reg_alpha': 6.55553371303814, 'reg_lambda': 7.855699980967506}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   48.5s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:20:30,379] Trial 83 finished with value: 1.340026563930323 and parameters: {'num_leaves': 256, 'max_depth': 6, 'learning_rate': 0.0023024605273033144, 'n_estimators': 655, 'min_split_gain': 0.07175681415585271, 'min_child_samples': 184, 'subsample': 0.7689250579019604, 'colsample_bytree': 0.8021054619515442, 'reg_alpha': 5.099116216138514, 'reg_lambda': 8.911302727207453}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   34.1s finished

[I 2025-06-25 18:20:34,197] Trial 84 finished with value: 1.3259449588179364 and parameters: {'num_leaves': 240, 'max_depth': 6, 'learning_rate': 0.0021631918172910877, 'n_estimators': 355, 'min_split_gain': 0.07046802055587989, 'min_child_samples': 185, 'subsample': 0.8079972113260978, 'colsample_bytree': 0.826178554765068, 'reg_alpha': 5.038480595102912, 'reg_lambda': 8.956390085346047}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   16.5s finished

[I 2025-06-25 18:20:40,684] Trial 85 finished with value: 1.3269394722060737 and parameters: {'num_leaves': 221, 'max_depth': 6, 'learning_rate': 0.002479353048603425, 'n_estimators': 442, 'min_split_gain': 0.061172910627905024, 'min_child_samples': 183, 'subsample': 0.7950908762196238, 'colsample_bytree': 0.8515437149618016, 'reg_alpha': 5.088226099159687, 'reg_lambda': 8.887728033240503}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   15.9s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:20:46,595] Trial 86 finished with value: 1.329994813389939 and parameters: {'num_leaves': 197, 'max_depth': 6, 'learning_rate': 0.0021867035265994354, 'n_estimators': 443, 'min_split_gain': 0.08706836955050849, 'min_child_samples': 201, 'subsample': 0.8105679917331078, 'colsample_bytree': 0.7852915838577187, 'reg_alpha': 3.0932147567332784, 'reg_lambda': 8.678779526782357}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   15.3s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:20:49,765] Trial 87 finished with value: 1.3316997284865584 and parameters: {'num_leaves': 220, 'max_depth': 4, 'learning_rate': 0.0015686068701147875, 'n_estimators': 439, 'min_split_gain': 0.08641664943629544, 'min_child_samples': 180, 'subsample': 0.7429478081029769, 'colsample_bytree': 0.8521281872649658, 'reg_alpha': 4.754763998163253, 'reg_lambda': 9.244754094053842}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   14.6s finished

[I 2025-06-25 18:20:55,789] Trial 88 finished with value: 1.3498714846153503 and parameters: {'num_leaves': 246, 'max_depth': 6, 'learning_rate': 0.005015941129457029, 'n_estimators': 357, 'min_split_gain': 0.06327224757606163, 'min_child_samples': 180, 'subsample': 0.7990642489971074, 'colsample_bytree': 0.8517091472408589, 'reg_alpha': 6.949675750933329, 'reg_lambda': 8.119164071303434}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   11.5s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:20:58,425] Trial 89 finished with value: 1.331114696271516 and parameters: {'num_leaves': 222, 'max_depth': 4, 'learning_rate': 0.003341579986809585, 'n_estimators': 356, 'min_split_gain': 0.06314394652437129, 'min_child_samples': 180, 'subsample': 0.7959784001687418, 'colsample_bytree': 0.8540010713476872, 'reg_alpha': 6.962265434703788, 'reg_lambda': 8.08174495381154}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   16.4s finished
[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.

[I 2025-06-25 18:21:06,483] Trial 90 finished with value: 1.3280135906337034 and parameters: {'num_leaves': 227, 'max_depth': 7, 'learning_rate': 0.002724229612979529, 'n_estimators': 360, 'min_split_gain': 0.05806987990174497, 'min_child_samples': 165, 'subsample': 0.7972669323176589, 'colsample_bytree': 0.8253409929320439, 'reg_alpha': 3.8477304707191067, 'reg_lambda': 8.112867173336857}. Best is trial 35 with value: 1.3254453900560412.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   17.9s finished

[I 2025-06-25 18:21:14,221] Trial 91 finished with value: 1.3235717967614486 and parameters: {'num_leaves': 226, 'max_depth': 7, 'learning_rate': 0.0025005781634419447, 'n_estimators': 301, 'min_split_gain': 0.062056017050348036, 'min_child_samples': 73, 'subsample': 0.7965393581941175, 'colsample_bytree': 0.8983356418768158, 'reg_alpha': 3.876073917292994, 'reg_lambda': 7.6338887754587}. Best is trial 91 with value: 1.3235717967614486.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   46.8s finished

[I 2025-06-25 18:21:45,715] Trial 92 finished with value: 1.3864466517507683 and parameters: {'num_leaves': 227, 'max_depth': 7, 'learning_rate': 0.0018036557415982274, 'n_estimators': 1416, 'min_split_gain': 0.06912934755830887, 'min_child_samples': 163, 'subsample': 0.7751924318707953, 'colsample_bytree': 0.8996352200218682, 'reg_alpha': 3.843131624445197, 'reg_lambda': 7.637582656538138}. Best is trial 91 with value: 1.3235717967614486.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   51.6s finished

[I 2025-06-25 18:22:06,289] Trial 94 finished with value: 1.3312512911559207 and parameters: {'num_leaves': 235, 'max_depth': 7, 'learning_rate': 0.002580740894471269, 'n_estimators': 334, 'min_split_gain': 0.058956477753904286, 'min_child_samples': 130, 'subsample': 0.7735120363602979, 'colsample_bytree': 0.8213534341321493, 'reg_alpha': 2.925082806456657, 'reg_lambda': 7.660439855129096}. Best is trial 91 with value: 1.3235717967614486.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:  1.0min finished

[I 2025-06-25 18:22:07,093] Trial 93 finished with value: 1.432706305168893 and parameters: {'num_leaves': 227, 'max_depth': 7, 'learning_rate': 0.0026292547666443423, 'n_estimators': 1435, 'min_split_gain': 0.0602775762528185, 'min_child_samples': 164, 'subsample': 0.8439214724397727, 'colsample_bytree': 0.8201956604383285, 'reg_alpha': 4.9807731756988485, 'reg_lambda': 8.53784535606538}. Best is trial 91 with value: 1.3235717967614486.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   28.4s finished

[I 2025-06-25 18:22:14,479] Trial 95 finished with value: 1.3232552977968914 and parameters: {'num_leaves': 235, 'max_depth': 7, 'learning_rate': 0.0025811700418779, 'n_estimators': 316, 'min_split_gain': 0.05689193905682844, 'min_child_samples': 74, 'subsample': 0.8407592573163879, 'colsample_bytree': 0.8275103979185824, 'reg_alpha': 3.068146873106655, 'reg_lambda': 9.007009925291273}. Best is trial 95 with value: 1.3232552977968914.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   15.0s finished

[I 2025-06-25 18:22:21,601] Trial 96 finished with value: 1.3215249360188743 and parameters: {'num_leaves': 249, 'max_depth': 7, 'learning_rate': 0.003128061264002138, 'n_estimators': 309, 'min_split_gain': 0.053229514472552364, 'min_child_samples': 83, 'subsample': 0.8404270616044334, 'colsample_bytree': 0.928531610035008, 'reg_alpha': 3.922107925798527, 'reg_lambda': 8.974618333106958}. Best is trial 96 with value: 1.3215249360188743.

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   18.4s finished

[I 2025-06-25 18:22:25,963] Trial 97 finished with value: 1.3304494493158006 and parameters: {'num_leaves': 253, 'max_depth': 6, 'learning_rate': 0.003167571938968424, 'n_estimators': 310, 'min_split_gain': 0.054774895867760846, 'min_child_samples': 205, 'subsample': 0.7956431532059667, 'colsample_bytree': 0.9000715287743534, 'reg_alpha': 3.866472724551117, 'reg_lambda': 9.129253384627228}. Best is trial 96 with value: 1.3215249360188743.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   16.6s finished

[I 2025-06-25 18:22:31,360] Trial 98 finished with value: 1.3234648216365306 and parameters: {'num_leaves': 250, 'max_depth': 6, 'learning_rate': 0.003187987435136451, 'n_estimators': 307, 'min_split_gain': 0.05183044861455714, 'min_child_samples': 72, 'subsample': 0.8104112736443542, 'colsample_bytree': 0.8922814041178597, 'reg_alpha': 3.4546194780846093, 'reg_lambda': 9.091968624583071}. Best is trial 96 with value: 1.3215249360188743.

[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   12.8s finished

[I 2025-06-25 18:22:34,955] Trial 99 finished with value: 1.3299093489757015 and parameters: {'num_leaves': 250, 'max_depth': 6, 'learning_rate': 0.0039319917541102015, 'n_estimators': 304, 'min_split_gain': 0.054127138523769686, 'min_child_samples': 71, 'subsample': 0.8385907687597056, 'colsample_bytree': 0.9622773607394488, 'reg_alpha': 2.4123020600943788, 'reg_lambda': 9.015557191549908}. Best is trial 96 with value: 1.3215249360188743.

In [190]:
# Optuna 결과
print('Best parameters:')
print(study.best_params)
print('Best RMSE:')
print(study.best_trial.value)

# 최적 파라미터 저장
with open('best_params.json', 'w') as f:
    json.dump({f'model__{k}': v for k, v in study.best_trial.params.items()}, f, indent = 4)

# 최적 RMSE 저장
with open('best_rmse.txt', 'w') as f:
    f.write(str(study.best_trial.value))

Best parameters:
{'num_leaves': 249, 'max_depth': 7, 'learning_rate': 0.003128061264002138, 'n_estimators': 309, 'min_split_gain': 0.053229514472552364, 'min_child_samples': 83, 'subsample': 0.8404270616044334, 'colsample_bytree': 0.928531610035008, 'reg_alpha': 3.922107925798527, 'reg_lambda': 8.974618333106958}
Best RMSE:
1.3215249360188743

In [8]:
# 전체 데이터로 재학습
with open('best_params.json', 'r') as f:
    best_params = json.load(f)

best_lgbm = pipeline.set_params(**best_params)
best_lgbm = best_lgbm.fit(x, y)

# RF

### 모형 선택 (RF)

In [9]:
# 모형 파이프라인
pipeline2 = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LGBMRegressor(
        boosting_type = 'rf',
        learning_rate = 1.0,
        objective = 'regression',
        bagging_freq = 1,
        min_child_samples = 1,
        random_state = 42, 
        boost_from_average = False,
        verbosity = -1, 
        device = 'gpu'
    ))
])

In [ ]:
# Optuna 목적 함수
def objective2(trial):
    params = {
        'model__num_leaves': trial.suggest_int('num_leaves', 128, 256),
        'model__n_estimators': trial.suggest_int('n_estimators', 300, 1000),
        'model__bagging_fraction': trial.suggest_float('bagging_fraction', 0.6, 0.9),
        'model__feature_fraction': trial.suggest_float('feature_fraction', 0.6, 0.9),
    }

    optuna_pipeline = clone(pipeline2).set_params(**params)

    scores = cross_validate(
        optuna_pipeline, x, y,
        scoring = 'neg_root_mean_squared_error',
        cv = cv,
        n_jobs = 4,
        verbose = 1
    )
    
    return -scores['test_score'].mean()

# Optuna 실행
os.environ['PYTHONHASHSEED'] = str(42)
sampler2 = optuna.samplers.TPESampler(seed = 42)
study2 = optuna.create_study(
    direction = 'minimize',
    study_name = 'predict_call_count2',
    sampler = sampler2
)
study2.optimize(objective2, n_trials = 50, n_jobs = 3, show_progress_bar = True)

In [ ]:
# Optuna 결과
print('Best parameters:')
print(study2.best_params)
print('Best RMSE:')
print(study2.best_trial.value)

# 최적 파라미터 저장
with open('best_params2.json', 'w') as f:
    json.dump({f'model__{k}': v for k, v in study2.best_trial.params.items()}, f, indent = 4)

# 최적 RMSE 저장
with open('best_rmse2.txt', 'w') as f:
    f.write(str(study2.best_trial.value))

In [10]:
# 전체 데이터로 재학습
with open('best_params2.json', 'r') as f:
    best_params2 = json.load(f)

best_rf = pipeline2.set_params(**best_params2)
best_rf = best_rf.fit(x, y)

# XGB

### 모형 선택 (XGB)

In [11]:
# 모형 파이프라인
pipeline3 = Pipeline([
    ('preprocessor', preprocessor),
    ('model', XGBRegressor(
        verbosity = 1,
        objective = 'reg:squarederror',
        random_state = 42,
        tree_method = 'hist',
        device = 'cuda'
    ))
])

In [193]:
# Optuna 목적 함수
def objective3(trial):
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 300, 2000),
        'model__max_depth': trial.suggest_int('max_depth', 4, 16),
        'model__min_child_weight': trial.suggest_int('min_child_weight', 1, 20),
        'model__gamma': trial.suggest_float('gamma', 0, 10.0),
        'model__learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.2, log = True),
        'model__subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'model__colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'model__reg_alpha': trial.suggest_float('reg_alpha', 0.0, 10.0),
        'model__reg_lambda': trial.suggest_float('reg_lambda', 0.0, 10.0)
    }

    optuna_pipeline = clone(pipeline3).set_params(**params)

    scores = cross_validate(
        optuna_pipeline, x, y,
        scoring = 'neg_root_mean_squared_error',
        cv = cv,
        n_jobs = 3,
        verbose = 1
    )
    
    return -scores['test_score'].mean()

# Optuna 실행
os.environ['PYTHONHASHSEED'] = str(42)
sampler3 = optuna.samplers.TPESampler(seed = 42)
study3 = optuna.create_study(
    direction = 'minimize',
    study_name = 'predict_call_count3',
    sampler = sampler3
)
study3.optimize(objective3, n_trials = 100, n_jobs = 3, show_progress_bar = True)

[I 2025-06-25 18:23:05,058] A new study created in memory with name: predict_call_count3

  0%|          | 0/100 [00:00<?, ?it/s]

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.0min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:24:06,811] Trial 2 finished with value: 1.8185342788696288 and parameters: {'n_estimators': 1061, 'max_depth': 8, 'min_child_weight': 8, 'gamma': 2.6529082185348143, 'learning_rate': 0.006937267597614984, 'subsample': 0.7084146753421238, 'colsample_bytree': 0.6816335951195884, 'reg_alpha': 0.3937051397680946, 'reg_lambda': 2.0816289651674857}. Best is trial 2 with value: 1.8185342788696288.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.2min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:24:17,307] Trial 0 finished with value: 1.691718626022339 and parameters: {'n_estimators': 564, 'max_depth': 9, 'min_child_weight': 12, 'gamma': 3.304189296428409, 'learning_rate': 0.02533076190990307, 'subsample': 0.6302462184534532, 'colsample_bytree': 0.5377650700495779, 'reg_alpha': 9.489004997589758, 'reg_lambda': 7.828869758156058}. Best is trial 0 with value: 1.691718626022339.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.9min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:24:59,840] Trial 1 finished with value: 1.7869872093200683 and parameters: {'n_estimators': 1544, 'max_depth': 14, 'min_child_weight': 3, 'gamma': 6.056988240577268, 'learning_rate': 0.0045464364114556795, 'subsample': 0.6001452075363322, 'colsample_bytree': 0.9968148518925104, 'reg_alpha': 0.8463084089771578, 'reg_lambda': 1.0617569515190306}. Best is trial 0 with value: 1.691718626022339.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  2.2min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:26:28,612] Trial 4 finished with value: 1.6918919324874877 and parameters: {'n_estimators': 846, 'max_depth': 13, 'min_child_weight': 14, 'gamma': 4.624425853993194, 'learning_rate': 0.12204862367027776, 'subsample': 0.9864920867948956, 'colsample_bytree': 0.5594797952672874, 'reg_alpha': 9.542096193636512, 'reg_lambda': 8.521393286099608}. Best is trial 0 with value: 1.691718626022339.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  2.5min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:26:36,151] Trial 3 finished with value: 1.6494841814041137 and parameters: {'n_estimators': 1893, 'max_depth': 15, 'min_child_weight': 12, 'gamma': 4.802473027580788, 'learning_rate': 0.0021804727417203333, 'subsample': 0.7850686687806321, 'colsample_bytree': 0.6891253139059941, 'reg_alpha': 4.467439777730004, 'reg_lambda': 2.23004538455665}. Best is trial 3 with value: 1.6494841814041137.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  3.3min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:28:15,914] Trial 5 finished with value: 1.4642950296401978 and parameters: {'n_estimators': 937, 'max_depth': 15, 'min_child_weight': 1, 'gamma': 1.439605757816208, 'learning_rate': 0.003050286314531697, 'subsample': 0.6208661526159409, 'colsample_bytree': 0.5120429131119384, 'reg_alpha': 2.161631726613823, 'reg_lambda': 3.177038350840937}. Best is trial 5 with value: 1.4642950296401978.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  2.0min finished

[I 2025-06-25 18:28:28,201] Trial 6 finished with value: 1.7573340654373169 and parameters: {'n_estimators': 781, 'max_depth': 12, 'min_child_weight': 7, 'gamma': 3.464282517043591, 'learning_rate': 0.03714708319181545, 'subsample': 0.676564169201281, 'colsample_bytree': 0.9578973023851769, 'reg_alpha': 6.069267190725908, 'reg_lambda': 7.3208148934244734}. Best is trial 5 with value: 1.4642950296401978.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.9min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:28:32,199] Trial 7 finished with value: 1.8201341390609742 and parameters: {'n_estimators': 496, 'max_depth': 13, 'min_child_weight': 16, 'gamma': 5.494917723399407, 'learning_rate': 0.13507180528788587, 'subsample': 0.6858318385735744, 'colsample_bytree': 0.957034859160742, 'reg_alpha': 0.9217787590929838, 'reg_lambda': 0.5509017017573692}. Best is trial 5 with value: 1.4642950296401978.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   31.4s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:28:47,580] Trial 8 finished with value: 1.5604743242263794 and parameters: {'n_estimators': 823, 'max_depth': 6, 'min_child_weight': 1, 'gamma': 9.52454116493948, 'learning_rate': 0.00639077248182402, 'subsample': 0.7611340390325011, 'colsample_bytree': 0.5680693966974922, 'reg_alpha': 6.464304104847156, 'reg_lambda': 3.0465225504285587}. Best is trial 5 with value: 1.4642950296401978.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   33.4s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:29:01,785] Trial 9 finished with value: 1.7634939670562744 and parameters: {'n_estimators': 1113, 'max_depth': 7, 'min_child_weight': 10, 'gamma': 9.270359599418946, 'learning_rate': 0.029338822729025923, 'subsample': 0.8638200925424249, 'colsample_bytree': 0.6511509251098864, 'reg_alpha': 3.746847712223458, 'reg_lambda': 2.018343836355241}. Best is trial 5 with value: 1.4642950296401978.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.4min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:29:53,969] Trial 10 finished with value: 1.4755306482315063 and parameters: {'n_estimators': 1222, 'max_depth': 16, 'min_child_weight': 16, 'gamma': 7.0698807111956485, 'learning_rate': 0.0024386044338663465, 'subsample': 0.9329281585991325, 'colsample_bytree': 0.6641732937340157, 'reg_alpha': 8.845684394964433, 'reg_lambda': 8.885156708272895}. Best is trial 5 with value: 1.4642950296401978.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  2.0min finished

[I 2025-06-25 18:30:49,583] Trial 11 finished with value: 1.792624568939209 and parameters: {'n_estimators': 1660, 'max_depth': 10, 'min_child_weight': 15, 'gamma': 1.2893143286250175, 'learning_rate': 0.017800847552200075, 'subsample': 0.6491949116130202, 'colsample_bytree': 0.5835971424054074, 'reg_alpha': 7.140506711081482, 'reg_lambda': 7.881618282502544}. Best is trial 5 with value: 1.4642950296401978.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  2.0min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:31:02,718] Trial 12 finished with value: 1.4038083791732787 and parameters: {'n_estimators': 1481, 'max_depth': 4, 'min_child_weight': 5, 'gamma': 0.04901722671604536, 'learning_rate': 0.0011086806729262743, 'subsample': 0.8943453057732018, 'colsample_bytree': 0.8063460609315245, 'reg_alpha': 2.5262419385254087, 'reg_lambda': 4.6656949592068715}. Best is trial 12 with value: 1.4038083791732787.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  3.7min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:33:34,063] Trial 13 finished with value: 1.490362572669983 and parameters: {'n_estimators': 1402, 'max_depth': 16, 'min_child_weight': 19, 'gamma': 0.26061130083922124, 'learning_rate': 0.0013199084230014464, 'subsample': 0.9090182660414194, 'colsample_bytree': 0.8086521318084409, 'reg_alpha': 3.1436962763784755, 'reg_lambda': 5.19793347316632}. Best is trial 12 with value: 1.4038083791732787.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  3.7min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:34:29,453] Trial 14 finished with value: 1.4448461055755615 and parameters: {'n_estimators': 1405, 'max_depth': 16, 'min_child_weight': 20, 'gamma': 7.244118769188103, 'learning_rate': 0.0011010342557149259, 'subsample': 0.8852692808267488, 'colsample_bytree': 0.8101597505807713, 'reg_alpha': 2.770187410225528, 'reg_lambda': 5.2072723353831005}. Best is trial 12 with value: 1.4038083791732787.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  3.6min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:34:40,648] Trial 15 finished with value: 1.3807157039642335 and parameters: {'n_estimators': 1411, 'max_depth': 4, 'min_child_weight': 5, 'gamma': 0.026518619084445083, 'learning_rate': 0.0010422433063053413, 'subsample': 0.8471254456672013, 'colsample_bytree': 0.8151649250092207, 'reg_alpha': 2.7057331127378865, 'reg_lambda': 5.281139272797359}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.5min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:35:07,061] Trial 16 finished with value: 1.413405704498291 and parameters: {'n_estimators': 1923, 'max_depth': 4, 'min_child_weight': 4, 'gamma': 0.03452948239075049, 'learning_rate': 0.0010960316341631147, 'subsample': 0.8605353573304342, 'colsample_bytree': 0.8239329834896956, 'reg_alpha': 2.2815356482286218, 'reg_lambda': 4.847033648690309}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:35:32,714] Trial 17 finished with value: 1.424612808227539 and parameters: {'n_estimators': 1982, 'max_depth': 4, 'min_child_weight': 6, 'gamma': 7.313892320033118, 'learning_rate': 0.0010430842858327692, 'subsample': 0.8359297174337396, 'colsample_bytree': 0.8201168093561583, 'reg_alpha': 2.2652794127213944, 'reg_lambda': 5.599043340826322}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.4min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:36:02,991] Trial 18 finished with value: 1.443187379837036 and parameters: {'n_estimators': 1918, 'max_depth': 5, 'min_child_weight': 6, 'gamma': 0.3671228077825513, 'learning_rate': 0.0010368709983188701, 'subsample': 0.8337634198153696, 'colsample_bytree': 0.860656744175174, 'reg_alpha': 1.9704883690030162, 'reg_lambda': 6.078014481146698}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.3min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:36:27,029] Trial 19 finished with value: 1.639530396461487 and parameters: {'n_estimators': 1737, 'max_depth': 4, 'min_child_weight': 6, 'gamma': 1.523523976274032, 'learning_rate': 0.009531928330668911, 'subsample': 0.8233842334247273, 'colsample_bytree': 0.8971281842827202, 'reg_alpha': 5.018721680112437, 'reg_lambda': 6.59968135964158}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.4min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:36:55,619] Trial 20 finished with value: 1.7113380908966065 and parameters: {'n_estimators': 1688, 'max_depth': 6, 'min_child_weight': 5, 'gamma': 1.6383149226495657, 'learning_rate': 0.010633369226135296, 'subsample': 0.9541279844932189, 'colsample_bytree': 0.8871096714842989, 'reg_alpha': 4.963984992300519, 'reg_lambda': 6.2776449332695865}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:37:10,837] Trial 21 finished with value: 1.667738127708435 and parameters: {'n_estimators': 1700, 'max_depth': 6, 'min_child_weight': 4, 'gamma': 1.8256656176000339, 'learning_rate': 0.06557336967138958, 'subsample': 0.9519099965498069, 'colsample_bytree': 0.7405107745930891, 'reg_alpha': 5.324692327232586, 'reg_lambda': 4.010013220244621}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   53.8s finished

[I 2025-06-25 18:37:21,296] Trial 22 finished with value: 1.771634292602539 and parameters: {'n_estimators': 1290, 'max_depth': 6, 'min_child_weight': 9, 'gamma': 2.055395928537089, 'learning_rate': 0.06470214179138645, 'subsample': 0.9528320278030115, 'colsample_bytree': 0.7339826036209331, 'reg_alpha': 4.2167007736915725, 'reg_lambda': 4.164626171380234}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   45.6s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:37:41,458] Trial 23 finished with value: 1.4612622261047363 and parameters: {'n_estimators': 1352, 'max_depth': 4, 'min_child_weight': 9, 'gamma': 0.05015215805016337, 'learning_rate': 0.0017555731772148845, 'subsample': 0.8736634616734603, 'colsample_bytree': 0.7433676516848386, 'reg_alpha': 1.5278873302755236, 'reg_lambda': 3.9757419598995067}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   49.3s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:38:00,392] Trial 24 finished with value: 1.4541614294052123 and parameters: {'n_estimators': 1330, 'max_depth': 4, 'min_child_weight': 9, 'gamma': 0.00381571499905823, 'learning_rate': 0.0018143629460019952, 'subsample': 0.8756516442028008, 'colsample_bytree': 0.7549450501405175, 'reg_alpha': 3.915601190132059, 'reg_lambda': 4.386883530209599}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   54.5s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:38:16,008] Trial 25 finished with value: 1.4648818969726562 and parameters: {'n_estimators': 1515, 'max_depth': 4, 'min_child_weight': 3, 'gamma': 0.05842187172204456, 'learning_rate': 0.001770954557194002, 'subsample': 0.8710852947924057, 'colsample_bytree': 0.7787001650715155, 'reg_alpha': 1.5815528878929654, 'reg_lambda': 4.188793707390984}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:38:45,784] Trial 26 finished with value: 1.570248508453369 and parameters: {'n_estimators': 1516, 'max_depth': 5, 'min_child_weight': 3, 'gamma': 0.6643754968897051, 'learning_rate': 0.003588290841376512, 'subsample': 0.773044139145282, 'colsample_bytree': 0.7833451626628729, 'reg_alpha': 3.3640920527165163, 'reg_lambda': 4.624797524543296}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.6min finished

[I 2025-06-25 18:39:36,349] Trial 27 finished with value: 1.5544761419296265 and parameters: {'n_estimators': 1543, 'max_depth': 8, 'min_child_weight': 3, 'gamma': 2.890816002491227, 'learning_rate': 0.00381479541245172, 'subsample': 0.7678455771411118, 'colsample_bytree': 0.849393781670719, 'reg_alpha': 3.1455662692919333, 'reg_lambda': 6.845330005331597}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  2.2min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:40:30,292] Trial 28 finished with value: 1.5435373783111572 and parameters: {'n_estimators': 1837, 'max_depth': 8, 'min_child_weight': 2, 'gamma': 0.8795325174890696, 'learning_rate': 0.0035687030626376116, 'subsample': 0.7640838648327601, 'colsample_bytree': 0.8558223596946973, 'reg_alpha': 3.366820160552121, 'reg_lambda': 6.848881295907069}. Best is trial 15 with value: 1.3807157039642335.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.7min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:41:16,640] Trial 30 finished with value: 1.3399828910827636 and parameters: {'n_estimators': 314, 'max_depth': 5, 'min_child_weight': 1, 'gamma': 0.9803598058990651, 'learning_rate': 0.001509986869976639, 'subsample': 0.7329081813307514, 'colsample_bytree': 0.9090535631179045, 'reg_alpha': 0.2392786563470226, 'reg_lambda': 5.74318689989658}. Best is trial 30 with value: 1.3399828910827636.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  2.6min finished

[I 2025-06-25 18:41:23,190] Trial 29 finished with value: 1.7438063383102418 and parameters: {'n_estimators': 1849, 'max_depth': 8, 'min_child_weight': 4, 'gamma': 3.0397478152861375, 'learning_rate': 0.0045871386442607265, 'subsample': 0.8114806640638988, 'colsample_bytree': 0.854028103500967, 'reg_alpha': 2.7283643672326536, 'reg_lambda': 3.194401714606566}. Best is trial 30 with value: 1.3399828910827636.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.3min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:41:50,882] Trial 31 finished with value: 1.3507404565811156 and parameters: {'n_estimators': 637, 'max_depth': 10, 'min_child_weight': 5, 'gamma': 3.6636070782778765, 'learning_rate': 0.001470650438962368, 'subsample': 0.8113533754284817, 'colsample_bytree': 0.9096132137596628, 'reg_alpha': 0.04976642125198216, 'reg_lambda': 9.714675394410662}. Best is trial 30 with value: 1.3399828910827636.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.2min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:42:26,954] Trial 32 finished with value: 1.3163363933563232 and parameters: {'n_estimators': 706, 'max_depth': 10, 'min_child_weight': 1, 'gamma': 4.221824093721579, 'learning_rate': 0.0015532389955239282, 'subsample': 0.7273859327224794, 'colsample_bytree': 0.9200042147135536, 'reg_alpha': 0.5180395786262285, 'reg_lambda': 9.92041385515991}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.2min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:42:34,852] Trial 33 finished with value: 1.3363121271133422 and parameters: {'n_estimators': 721, 'max_depth': 5, 'min_child_weight': 1, 'gamma': 0.8939170883171422, 'learning_rate': 0.001456250462675229, 'subsample': 0.7329189504875648, 'colsample_bytree': 0.9174710991023306, 'reg_alpha': 0.02113553870157614, 'reg_lambda': 5.59380180736707}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.0min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:42:52,361] Trial 34 finished with value: 1.3552801847457885 and parameters: {'n_estimators': 329, 'max_depth': 10, 'min_child_weight': 7, 'gamma': 2.422267351150448, 'learning_rate': 0.0014368862882508594, 'subsample': 0.7365436140290268, 'colsample_bytree': 0.9449260331739924, 'reg_alpha': 0.22519423498444557, 'reg_lambda': 9.422697632739204}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   39.7s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:43:06,909] Trial 35 finished with value: 1.3417614936828612 and parameters: {'n_estimators': 318, 'max_depth': 11, 'min_child_weight': 1, 'gamma': 3.6087741451673043, 'learning_rate': 0.0016049610885185597, 'subsample': 0.7249454387804103, 'colsample_bytree': 0.9342707038930513, 'reg_alpha': 0.15841407481139502, 'reg_lambda': 9.812988671301172}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   47.8s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:43:22,890] Trial 36 finished with value: 1.3244553565979005 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_child_weight': 1, 'gamma': 3.8605194925552913, 'learning_rate': 0.0024613298319575896, 'subsample': 0.7385114903286606, 'colsample_bytree': 0.9290597159739239, 'reg_alpha': 0.010022300027347275, 'reg_lambda': 9.872107382018422}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.0min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:43:53,668] Trial 37 finished with value: 1.3257508993148803 and parameters: {'n_estimators': 641, 'max_depth': 9, 'min_child_weight': 1, 'gamma': 3.715630533657599, 'learning_rate': 0.0025805503677580107, 'subsample': 0.7299516745945239, 'colsample_bytree': 0.9943347287557774, 'reg_alpha': 0.6634718028811948, 'reg_lambda': 9.932571917044118}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.0min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:44:08,120] Trial 38 finished with value: 1.3247701406478882 and parameters: {'n_estimators': 311, 'max_depth': 11, 'min_child_weight': 1, 'gamma': 4.057919046703475, 'learning_rate': 0.0027517328785942236, 'subsample': 0.7272187005001223, 'colsample_bytree': 0.9935346148609538, 'reg_alpha': 0.7396949779502221, 'reg_lambda': 8.511512570451758}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:44:27,745] Trial 39 finished with value: 1.328730583190918 and parameters: {'n_estimators': 473, 'max_depth': 9, 'min_child_weight': 2, 'gamma': 4.18856695305668, 'learning_rate': 0.002681344861154376, 'subsample': 0.7081217780705835, 'colsample_bytree': 0.9976264730204363, 'reg_alpha': 0.9833678076930603, 'reg_lambda': 8.275583483959501}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   57.7s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:44:51,543] Trial 40 finished with value: 1.3421802282333375 and parameters: {'n_estimators': 656, 'max_depth': 9, 'min_child_weight': 2, 'gamma': 4.265515163009109, 'learning_rate': 0.0025416528177140047, 'subsample': 0.6976711146864338, 'colsample_bytree': 0.9935851225363852, 'reg_alpha': 0.9691106879813722, 'reg_lambda': 8.594835484200207}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.0min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:45:10,943] Trial 41 finished with value: 1.3229192256927491 and parameters: {'n_estimators': 467, 'max_depth': 9, 'min_child_weight': 2, 'gamma': 4.281250130963229, 'learning_rate': 0.0024949030457131786, 'subsample': 0.6962378753133148, 'colsample_bytree': 0.9957835306802707, 'reg_alpha': 0.9484396276144207, 'reg_lambda': 8.799703684404497}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.4min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:45:49,339] Trial 42 finished with value: 1.5953355073928832 and parameters: {'n_estimators': 930, 'max_depth': 12, 'min_child_weight': 12, 'gamma': 5.402463499496168, 'learning_rate': 0.005969959147210038, 'subsample': 0.6793363706836961, 'colsample_bytree': 0.9760480188408366, 'reg_alpha': 0.8900258889407272, 'reg_lambda': 9.086920779691564}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.4min finished

[I 2025-06-25 18:46:13,634] Trial 43 finished with value: 1.4098725080490113 and parameters: {'n_estimators': 509, 'max_depth': 11, 'min_child_weight': 2, 'gamma': 5.301173496949719, 'learning_rate': 0.005316631993341823, 'subsample': 0.6588478874657845, 'colsample_bytree': 0.9878634689508065, 'reg_alpha': 0.8359225889546822, 'reg_lambda': 8.063167685877861}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.3min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:46:31,312] Trial 44 finished with value: 1.4011425733566285 and parameters: {'n_estimators': 475, 'max_depth': 11, 'min_child_weight': 2, 'gamma': 5.450154401631105, 'learning_rate': 0.00692525087816077, 'subsample': 0.6541964114559845, 'colsample_bytree': 0.9728971269294014, 'reg_alpha': 1.3026721642092345, 'reg_lambda': 9.136106212101264}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:46:53,269] Trial 45 finished with value: 1.3493712425231934 and parameters: {'n_estimators': 442, 'max_depth': 11, 'min_child_weight': 2, 'gamma': 5.098050284663647, 'learning_rate': 0.004833829262355048, 'subsample': 0.6538827050669958, 'colsample_bytree': 0.9695739904905855, 'reg_alpha': 1.4756510297700738, 'reg_lambda': 9.316935894470591}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.0min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:47:14,051] Trial 46 finished with value: 1.3203202724456786 and parameters: {'n_estimators': 419, 'max_depth': 11, 'min_child_weight': 3, 'gamma': 6.127298924287086, 'learning_rate': 0.0020850570383514214, 'subsample': 0.6301316076359182, 'colsample_bytree': 0.9667689393194145, 'reg_alpha': 1.6394713448857345, 'reg_lambda': 7.503699589914717}. Best is trial 32 with value: 1.3163363933563232.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   54.9s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:47:26,378] Trial 47 finished with value: 1.2999507904052734 and parameters: {'n_estimators': 416, 'max_depth': 9, 'min_child_weight': 1, 'gamma': 6.248207339699165, 'learning_rate': 0.00326321672789249, 'subsample': 0.6198628101466246, 'colsample_bytree': 0.9608626104979301, 'reg_alpha': 0.6832534327076716, 'reg_lambda': 9.937464067042352}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   50.2s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:47:43,671] Trial 48 finished with value: 1.3370732307434081 and parameters: {'n_estimators': 403, 'max_depth': 9, 'min_child_weight': 1, 'gamma': 4.519789120866989, 'learning_rate': 0.002209441680400842, 'subsample': 0.7889099036814154, 'colsample_bytree': 0.9415941502643703, 'reg_alpha': 1.8355472387805953, 'reg_lambda': 7.491676962230166}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   53.5s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:48:07,710] Trial 49 finished with value: 1.3193219423294067 and parameters: {'n_estimators': 393, 'max_depth': 12, 'min_child_weight': 3, 'gamma': 6.124677710693141, 'learning_rate': 0.002164085754798399, 'subsample': 0.6185433837482989, 'colsample_bytree': 0.9351800016347764, 'reg_alpha': 0.538051329174114, 'reg_lambda': 7.574726139192009}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   58.2s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:48:24,863] Trial 50 finished with value: 1.3186552047729492 and parameters: {'n_estimators': 392, 'max_depth': 12, 'min_child_weight': 3, 'gamma': 6.027691772985213, 'learning_rate': 0.0020789289027513106, 'subsample': 0.6040376456046588, 'colsample_bytree': 0.9374479140784263, 'reg_alpha': 1.6299414359269888, 'reg_lambda': 7.362523798312853}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:48:51,109] Trial 51 finished with value: 1.3149090051651 and parameters: {'n_estimators': 544, 'max_depth': 13, 'min_child_weight': 3, 'gamma': 6.216242059368022, 'learning_rate': 0.0020577959847360456, 'subsample': 0.6030698666366556, 'colsample_bytree': 0.876538037202508, 'reg_alpha': 8.835204421068264, 'reg_lambda': 7.476333885136498}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished

[I 2025-06-25 18:49:16,917] Trial 52 finished with value: 1.4417089223861694 and parameters: {'n_estimators': 569, 'max_depth': 13, 'min_child_weight': 3, 'gamma': 6.019550882177864, 'learning_rate': 0.008564669059478553, 'subsample': 0.6059147307504783, 'colsample_bytree': 0.877461570467421, 'reg_alpha': 8.008906681605852, 'reg_lambda': 7.512267047322507}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.3min finished

[I 2025-06-25 18:49:44,886] Trial 53 finished with value: 1.3239162683486938 and parameters: {'n_estimators': 564, 'max_depth': 13, 'min_child_weight': 3, 'gamma': 6.205466975105114, 'learning_rate': 0.0020185569101668047, 'subsample': 0.6037987238692297, 'colsample_bytree': 0.9567538681850694, 'reg_alpha': 0.5298868872695854, 'reg_lambda': 7.617418051673035}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.4min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:50:14,035] Trial 54 finished with value: 1.3187576293945313 and parameters: {'n_estimators': 567, 'max_depth': 14, 'min_child_weight': 3, 'gamma': 6.25063715642046, 'learning_rate': 0.0020707348105134527, 'subsample': 0.6187739794968272, 'colsample_bytree': 0.8769381024163758, 'reg_alpha': 8.834287897860422, 'reg_lambda': 7.465639411700972}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.4min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:50:41,968] Trial 55 finished with value: 1.3293434143066407 and parameters: {'n_estimators': 583, 'max_depth': 14, 'min_child_weight': 4, 'gamma': 6.632397822306707, 'learning_rate': 0.001964279356672837, 'subsample': 0.6268130607492992, 'colsample_bytree': 0.9591553051631423, 'reg_alpha': 9.354621850958873, 'reg_lambda': 7.122779632232253}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.2min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:50:56,061] Trial 56 finished with value: 1.333362889289856 and parameters: {'n_estimators': 394, 'max_depth': 14, 'min_child_weight': 4, 'gamma': 6.788471465970734, 'learning_rate': 0.003326410204191088, 'subsample': 0.6317088971884263, 'colsample_bytree': 0.8851373598771063, 'reg_alpha': 7.226189056768059, 'reg_lambda': 7.159875398761163}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   50.3s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:51:04,547] Trial 57 finished with value: 1.7209463357925414 and parameters: {'n_estimators': 771, 'max_depth': 14, 'min_child_weight': 4, 'gamma': 7.97963744649255, 'learning_rate': 0.19751877083802127, 'subsample': 0.6197433607934272, 'colsample_bytree': 0.8747398169961778, 'reg_alpha': 9.09325830723758, 'reg_lambda': 7.093670242197949}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   44.5s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:51:26,766] Trial 58 finished with value: 1.67694411277771 and parameters: {'n_estimators': 791, 'max_depth': 14, 'min_child_weight': 7, 'gamma': 7.994275443021565, 'learning_rate': 0.017484805328810627, 'subsample': 0.6408401361020623, 'colsample_bytree': 0.886528963435812, 'reg_alpha': 8.30540757118342, 'reg_lambda': 8.174642284015974}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   58.1s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:51:54,465] Trial 59 finished with value: 1.3217237949371339 and parameters: {'n_estimators': 756, 'max_depth': 12, 'min_child_weight': 7, 'gamma': 8.051896730920012, 'learning_rate': 0.0012343213772253254, 'subsample': 0.6157961907652703, 'colsample_bytree': 0.6096664987356242, 'reg_alpha': 8.564923871538149, 'reg_lambda': 7.98820626635303}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:52:11,743] Trial 60 finished with value: 1.5822676181793214 and parameters: {'n_estimators': 896, 'max_depth': 12, 'min_child_weight': 5, 'gamma': 8.018696279386576, 'learning_rate': 0.01626963330211337, 'subsample': 0.6418556158207596, 'colsample_bytree': 0.9219058826974978, 'reg_alpha': 9.993964822597945, 'reg_lambda': 7.992794330848016}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.4min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:52:50,013] Trial 61 finished with value: 1.3320915460586549 and parameters: {'n_estimators': 899, 'max_depth': 12, 'min_child_weight': 5, 'gamma': 7.776970126001451, 'learning_rate': 0.0012386819726712887, 'subsample': 0.6124742978362293, 'colsample_bytree': 0.8353142008632167, 'reg_alpha': 9.926775540317198, 'reg_lambda': 6.329508622865821}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.3min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:53:13,737] Trial 62 finished with value: 1.3879578590393067 and parameters: {'n_estimators': 531, 'max_depth': 15, 'min_child_weight': 18, 'gamma': 5.903095593876881, 'learning_rate': 0.0032157825637647267, 'subsample': 0.666181220725629, 'colsample_bytree': 0.9195016744006008, 'reg_alpha': 7.7638155288890776, 'reg_lambda': 6.364678507420491}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.3min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:53:29,495] Trial 63 finished with value: 1.3263492345809937 and parameters: {'n_estimators': 409, 'max_depth': 13, 'min_child_weight': 3, 'gamma': 5.948873109202157, 'learning_rate': 0.0031168207225334642, 'subsample': 0.6656251998314281, 'colsample_bytree': 0.8394984673441083, 'reg_alpha': 7.603672452933203, 'reg_lambda': 6.367554867733569}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.0min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:53:52,718] Trial 64 finished with value: 1.3202615261077881 and parameters: {'n_estimators': 399, 'max_depth': 15, 'min_child_weight': 3, 'gamma': 5.8698828838746175, 'learning_rate': 0.0030777960989668415, 'subsample': 0.6373719793432189, 'colsample_bytree': 0.8982850372276656, 'reg_alpha': 7.457030145762124, 'reg_lambda': 6.666311882754144}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.4min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:54:40,186] Trial 65 finished with value: 1.6396334648132325 and parameters: {'n_estimators': 1037, 'max_depth': 13, 'min_child_weight': 3, 'gamma': 6.3542420654608165, 'learning_rate': 0.004149695392046058, 'subsample': 0.6336541427790893, 'colsample_bytree': 0.89717749760461, 'reg_alpha': 6.368491984546453, 'reg_lambda': 1.6826582138460369}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.9min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:55:22,050] Trial 66 finished with value: 1.411212396621704 and parameters: {'n_estimators': 1014, 'max_depth': 12, 'min_child_weight': 13, 'gamma': 6.597869553577112, 'learning_rate': 0.002053899821140625, 'subsample': 0.6000693026737689, 'colsample_bytree': 0.9055291441466712, 'reg_alpha': 1.3282165841644928, 'reg_lambda': 7.7138066857307725}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  2.2min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:56:02,998] Trial 67 finished with value: 1.525050401687622 and parameters: {'n_estimators': 1019, 'max_depth': 15, 'min_child_weight': 13, 'gamma': 4.863001670778816, 'learning_rate': 0.0039594882347143475, 'subsample': 0.6016610266335082, 'colsample_bytree': 0.8965010554939988, 'reg_alpha': 6.377950890136335, 'reg_lambda': 6.736481639960797}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.7min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:56:21,639] Trial 68 finished with value: 1.3303676128387452 and parameters: {'n_estimators': 373, 'max_depth': 15, 'min_child_weight': 13, 'gamma': 4.859775682829833, 'learning_rate': 0.0018163349344889547, 'subsample': 0.6012054658209661, 'colsample_bytree': 0.9464447890272331, 'reg_alpha': 5.858813313440763, 'reg_lambda': 6.761651657938924}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.3min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:56:40,534] Trial 69 finished with value: 1.3245277166366578 and parameters: {'n_estimators': 376, 'max_depth': 15, 'min_child_weight': 4, 'gamma': 4.919403424956008, 'learning_rate': 0.0016843849430024196, 'subsample': 0.6429609870047068, 'colsample_bytree': 0.8684670422781646, 'reg_alpha': 8.715334021327083, 'reg_lambda': 8.723663415803866}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.2min finished

[I 2025-06-25 18:57:16,568] Trial 70 finished with value: 1.4085847854614257 and parameters: {'n_estimators': 692, 'max_depth': 16, 'min_child_weight': 4, 'gamma': 7.065717479376376, 'learning_rate': 0.0029328792226459397, 'subsample': 0.6436963375675732, 'colsample_bytree': 0.8678980521903767, 'reg_alpha': 5.584086688539801, 'reg_lambda': 5.927027890674926}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.2min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:57:34,276] Trial 71 finished with value: 1.6418523788452148 and parameters: {'n_estimators': 680, 'max_depth': 14, 'min_child_weight': 6, 'gamma': 6.863755435790588, 'learning_rate': 0.022023006527163595, 'subsample': 0.6439801459569073, 'colsample_bytree': 0.8712503749806116, 'reg_alpha': 8.874921657393756, 'reg_lambda': 9.561306765141413}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:57:47,094] Trial 72 finished with value: 1.325110411643982 and parameters: {'n_estimators': 697, 'max_depth': 7, 'min_child_weight': 6, 'gamma': 5.754424992408727, 'learning_rate': 0.0012811880499586387, 'subsample': 0.6198825798682264, 'colsample_bytree': 0.9317775995785955, 'reg_alpha': 8.936985527898532, 'reg_lambda': 8.446957147029558}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:58:22,819] Trial 73 finished with value: 1.3739272117614747 and parameters: {'n_estimators': 611, 'max_depth': 13, 'min_child_weight': 6, 'gamma': 5.726082389364893, 'learning_rate': 0.002186383100178145, 'subsample': 0.6155641850939787, 'colsample_bytree': 0.9567762942583242, 'reg_alpha': 1.849881112562243, 'reg_lambda': 7.3427379920689075}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.2min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:58:43,987] Trial 74 finished with value: 1.3147443532943726 and parameters: {'n_estimators': 516, 'max_depth': 10, 'min_child_weight': 3, 'gamma': 5.645595531816499, 'learning_rate': 0.0021682188177464157, 'subsample': 0.6165338179376949, 'colsample_bytree': 0.9548927647448756, 'reg_alpha': 2.32593182993301, 'reg_lambda': 8.378823272131736}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.3min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:59:06,219] Trial 75 finished with value: 1.328879427909851 and parameters: {'n_estimators': 605, 'max_depth': 10, 'min_child_weight': 3, 'gamma': 5.729730907253634, 'learning_rate': 0.002055174587312968, 'subsample': 0.628446297794785, 'colsample_bytree': 0.9538079794028845, 'reg_alpha': 1.8225268292850085, 'reg_lambda': 7.291164102220183}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.0min finished

[I 2025-06-25 18:59:24,751] Trial 76 finished with value: 1.319004511833191 and parameters: {'n_estimators': 535, 'max_depth': 10, 'min_child_weight': 3, 'gamma': 7.416050674863593, 'learning_rate': 0.00224833473299608, 'subsample': 0.629740496541688, 'colsample_bytree': 0.9424740565778889, 'reg_alpha': 6.880568725784566, 'reg_lambda': 7.791207574595337}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   51.9s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:59:36,215] Trial 77 finished with value: 1.5226035356521606 and parameters: {'n_estimators': 524, 'max_depth': 10, 'min_child_weight': 2, 'gamma': 7.383809366903581, 'learning_rate': 0.035449922547454826, 'subsample': 0.6722150736275553, 'colsample_bytree': 0.6902830572960863, 'reg_alpha': 6.8875326477529155, 'reg_lambda': 9.062473975850493}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   41.7s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 18:59:48,138] Trial 78 finished with value: 1.3282886266708374 and parameters: {'n_estimators': 360, 'max_depth': 10, 'min_child_weight': 2, 'gamma': 7.501614014068826, 'learning_rate': 0.0016182292527014616, 'subsample': 0.6737759706263647, 'colsample_bytree': 0.715182829369711, 'reg_alpha': 0.5145161125772663, 'reg_lambda': 9.033418815234791}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   47.0s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:00:11,958] Trial 79 finished with value: 1.3138083934783935 and parameters: {'n_estimators': 525, 'max_depth': 10, 'min_child_weight': 2, 'gamma': 7.516785948864442, 'learning_rate': 0.001597587729665526, 'subsample': 0.6641506933792269, 'colsample_bytree': 0.9784546525785871, 'reg_alpha': 2.3711610834336625, 'reg_lambda': 9.021390775001898}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   53.1s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:00:29,624] Trial 80 finished with value: 1.3157872200012206 and parameters: {'n_estimators': 538, 'max_depth': 8, 'min_child_weight': 2, 'gamma': 8.686523849989655, 'learning_rate': 0.0015483092443505026, 'subsample': 0.6837097259834738, 'colsample_bytree': 0.9367910027995796, 'reg_alpha': 1.1770694025668642, 'reg_lambda': 8.40786991195664}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   53.6s finished

[I 2025-06-25 19:00:42,197] Trial 81 finished with value: 1.3286365747451783 and parameters: {'n_estimators': 524, 'max_depth': 8, 'min_child_weight': 1, 'gamma': 6.4236195295483585, 'learning_rate': 0.0010149579765457578, 'subsample': 0.6120120598682428, 'colsample_bytree': 0.9378990928049059, 'reg_alpha': 1.1491051334392157, 'reg_lambda': 8.339996308938069}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   48.6s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:01:00,860] Trial 82 finished with value: 1.3196988344192504 and parameters: {'n_estimators': 535, 'max_depth': 8, 'min_child_weight': 1, 'gamma': 8.61682762690085, 'learning_rate': 0.0013015557456155602, 'subsample': 0.7483445940123826, 'colsample_bytree': 0.9797114256304437, 'reg_alpha': 2.32813860911082, 'reg_lambda': 9.474267299781618}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   50.0s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:01:19,900] Trial 83 finished with value: 1.313964033126831 and parameters: {'n_estimators': 545, 'max_depth': 8, 'min_child_weight': 1, 'gamma': 8.547110434742663, 'learning_rate': 0.0013680254306297362, 'subsample': 0.6821322774723546, 'colsample_bytree': 0.9826784880634453, 'reg_alpha': 2.4412924273647794, 'reg_lambda': 9.516184189080638}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   47.2s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:01:29,550] Trial 84 finished with value: 1.3231644868850707 and parameters: {'n_estimators': 466, 'max_depth': 8, 'min_child_weight': 2, 'gamma': 8.542108962710852, 'learning_rate': 0.001344463268316895, 'subsample': 0.6880817495907114, 'colsample_bytree': 0.9758425918730813, 'reg_alpha': 2.2346573752418903, 'reg_lambda': 9.570864141823614}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   41.3s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:01:42,444] Trial 85 finished with value: 1.3175182819366456 and parameters: {'n_estimators': 452, 'max_depth': 7, 'min_child_weight': 2, 'gamma': 8.630048331782644, 'learning_rate': 0.0014495778627156275, 'subsample': 0.687471581681329, 'colsample_bytree': 0.9154491693133264, 'reg_alpha': 3.013506803074061, 'reg_lambda': 9.632546922998179}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   35.3s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:01:55,449] Trial 86 finished with value: 1.3155275344848634 and parameters: {'n_estimators': 456, 'max_depth': 7, 'min_child_weight': 2, 'gamma': 9.036785962939575, 'learning_rate': 0.0014648321601821235, 'subsample': 0.6864701586663904, 'colsample_bytree': 0.9183211746712865, 'reg_alpha': 2.46935395756723, 'reg_lambda': 9.966017180953813}. Best is trial 47 with value: 1.2999507904052734.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   55.0s finished

[I 2025-06-25 19:02:24,927] Trial 87 finished with value: 1.299101209640503 and parameters: {'n_estimators': 1156, 'max_depth': 7, 'min_child_weight': 1, 'gamma': 9.199870301367593, 'learning_rate': 0.001148678158231334, 'subsample': 0.7019023347657453, 'colsample_bytree': 0.9209639998918736, 'reg_alpha': 3.7038439028432055, 'reg_lambda': 9.988487086595121}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   50.7s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:02:33,427] Trial 88 finished with value: 1.327851366996765 and parameters: {'n_estimators': 445, 'max_depth': 7, 'min_child_weight': 1, 'gamma': 9.930581237832103, 'learning_rate': 0.0011545643669429383, 'subsample': 0.7038496318365607, 'colsample_bytree': 0.9223005967624283, 'reg_alpha': 2.990474542262789, 'reg_lambda': 9.979621670490229}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   49.6s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:02:45,297] Trial 89 finished with value: 1.3288933277130126 and parameters: {'n_estimators': 443, 'max_depth': 7, 'min_child_weight': 1, 'gamma': 9.779950858769594, 'learning_rate': 0.0011469001403865754, 'subsample': 0.7149925576499091, 'colsample_bytree': 0.9159733289037136, 'reg_alpha': 2.857313257523712, 'reg_lambda': 9.9576350877477}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   53.8s finished

[I 2025-06-25 19:03:19,212] Trial 90 finished with value: 1.3192511558532716 and parameters: {'n_estimators': 1156, 'max_depth': 7, 'min_child_weight': 1, 'gamma': 9.627801989619554, 'learning_rate': 0.0016744062749354948, 'subsample': 0.7088656699107062, 'colsample_bytree': 0.9811187619948136, 'reg_alpha': 3.8832820615159296, 'reg_lambda': 9.959808269759522}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.4min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:04:00,577] Trial 91 finished with value: 1.331316590309143 and parameters: {'n_estimators': 1111, 'max_depth': 9, 'min_child_weight': 1, 'gamma': 9.168904455077767, 'learning_rate': 0.0017872021824168302, 'subsample': 0.715285836912821, 'colsample_bytree': 0.9644057191364985, 'reg_alpha': 4.055857929800871, 'reg_lambda': 9.311398055993806}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.9min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:04:38,783] Trial 92 finished with value: 1.3321770906448365 and parameters: {'n_estimators': 1289, 'max_depth': 9, 'min_child_weight': 1, 'gamma': 9.034139386556486, 'learning_rate': 0.0016341866743146754, 'subsample': 0.6832907461506919, 'colsample_bytree': 0.9646309835137394, 'reg_alpha': 3.797884136436271, 'reg_lambda': 9.252239657152826}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.8min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:05:04,545] Trial 93 finished with value: 1.3240720987319947 and parameters: {'n_estimators': 1221, 'max_depth': 6, 'min_child_weight': 2, 'gamma': 9.232005960932389, 'learning_rate': 0.0014692272553387309, 'subsample': 0.6893518185944705, 'colsample_bytree': 0.9677968056360668, 'reg_alpha': 2.5437453231386598, 'reg_lambda': 9.252383884192522}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.5min finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:05:28,207] Trial 94 finished with value: 1.3125680446624757 and parameters: {'n_estimators': 1206, 'max_depth': 6, 'min_child_weight': 2, 'gamma': 9.067180202983932, 'learning_rate': 0.0013401737254499987, 'subsample': 0.6864171749526152, 'colsample_bytree': 0.9536333379197622, 'reg_alpha': 3.4945354893095137, 'reg_lambda': 9.735915875272605}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   56.3s finished
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.

[I 2025-06-25 19:05:35,396] Trial 95 finished with value: 1.311255645751953 and parameters: {'n_estimators': 505, 'max_depth': 6, 'min_child_weight': 2, 'gamma': 8.677109632755323, 'learning_rate': 0.0014655109501800802, 'subsample': 0.690011222536271, 'colsample_bytree': 0.9499431325916278, 'reg_alpha': 3.4807930802253093, 'reg_lambda': 9.647514000896136}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   41.6s finished

[I 2025-06-25 19:05:46,585] Trial 96 finished with value: 1.3114641904830933 and parameters: {'n_estimators': 494, 'max_depth': 6, 'min_child_weight': 2, 'gamma': 8.621315833985033, 'learning_rate': 0.0014144726319916471, 'subsample': 0.6576719367574368, 'colsample_bytree': 0.9499102538459664, 'reg_alpha': 3.4702064597745172, 'reg_lambda': 8.832183353489153}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   42.8s finished

[I 2025-06-25 19:06:11,286] Trial 97 finished with value: 1.338578462600708 and parameters: {'n_estimators': 1199, 'max_depth': 6, 'min_child_weight': 11, 'gamma': 8.910945010884147, 'learning_rate': 0.0010362969588799495, 'subsample': 0.6644498626346816, 'colsample_bytree': 0.9553123698167058, 'reg_alpha': 4.545451575785244, 'reg_lambda': 8.881056107981443}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.0min finished

[I 2025-06-25 19:06:37,736] Trial 98 finished with value: 1.360011601448059 and parameters: {'n_estimators': 1225, 'max_depth': 6, 'min_child_weight': 10, 'gamma': 8.42502138104524, 'learning_rate': 0.001193589911999935, 'subsample': 0.6978234362320678, 'colsample_bytree': 0.9843735613392856, 'reg_alpha': 4.584931529464727, 'reg_lambda': 8.7668934112479}. Best is trial 87 with value: 1.299101209640503.

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:  1.1min finished

[I 2025-06-25 19:06:54,208] Trial 99 finished with value: 1.3036813974380492 and parameters: {'n_estimators': 1160, 'max_depth': 6, 'min_child_weight': 2, 'gamma': 8.356239738624403, 'learning_rate': 0.0010208913685362641, 'subsample': 0.663201267533237, 'colsample_bytree': 0.9505895962667286, 'reg_alpha': 3.5143654737303014, 'reg_lambda': 8.871362346338135}. Best is trial 87 with value: 1.299101209640503.

In [194]:
# Optuna 결과
print('Best parameters:')
print(study3.best_params)
print('Best RMSE:')
print(study3.best_trial.value)

# 최적 파라미터 저장
with open('best_params3.json', 'w') as f:
    json.dump({f'model__{k}': v for k, v in study3.best_trial.params.items()}, f, indent = 4)

# 최적 RMSE 저장
with open('best_rmse3.txt', 'w') as f:
    f.write(str(study3.best_trial.value))

Best parameters:
{'n_estimators': 1156, 'max_depth': 7, 'min_child_weight': 1, 'gamma': 9.199870301367593, 'learning_rate': 0.001148678158231334, 'subsample': 0.7019023347657453, 'colsample_bytree': 0.9209639998918736, 'reg_alpha': 3.7038439028432055, 'reg_lambda': 9.988487086595121}
Best RMSE:
1.299101209640503

In [12]:
# 전체 데이터로 재학습
with open('best_params3.json', 'r') as f:
    best_params3 = json.load(f)

best_xgb = pipeline3.set_params(**best_params3)
best_xgb = best_xgb.fit(x, y)

# 앙상블

### 일단은 덜 엄밀한 버전: 이 버전의 CV RMSE는 과소추정! 다 돌리고 여유가 되면 엄밀버전도 해볼게요!

In [38]:
# 찾아낸 최적 모형들의 예측값으로 ridge regression (메타 모형): CV RMSE를 최소화하는 regularization parameter alpha 탐색
from sklearn.linear_model import RidgeCV

# RidgeCV
alpha_grid = np.logspace(-3, 2, 20)
ridge_cv = RidgeCV(alphas = alpha_grid, cv = cv)

# StackingRegressor를 위해 XGBoost의 device를 변경 (안 그러면 warning 나옴)
best_xgb.set_params(model__device = 'cpu')

# Base estimators
estimators = [
    ('lgbm', best_lgbm),
    ('rf', best_rf),
    ('xgb', best_xgb)
]

# Stacking 모델
stacked_model = StackingRegressor(
    estimators = estimators,
    final_estimator = ridge_cv,
    cv = 'prefit', # 'prefit': 원래는 매 fold를 학습하고 validate해야 하지만, 일단은 너무 오래걸려서 고정된 예측값만 사용
    passthrough = False,
    verbose = 1
)

# 학습
stacked_model.fit(x, y)

# 최적 alpha
print(f'Selected alpha: {stacked_model.final_estimator_.alpha_}')
print(f'Coefficients:{stacked_model.final_estimator_.coef_}')

Selected alpha: 100.0
Coefficients:[-0.44781222  1.28481887  0.01554073]

In [39]:
# 비교를 위한 CV RMSE 계산
meta_features = np.column_stack([
    best_lgbm.predict(x),
    best_rf.predict(x),
    best_xgb.predict(x)
])
scores = cross_validate(ridge_cv, meta_features, y, scoring='neg_root_mean_squared_error', cv = cv)

print("Ensemble RMSE:", -scores['test_score'].mean())

Ensemble RMSE: 1.0423938400653376

In [41]:
# 예측
submission = stacked_model.predict(x_test)
submission = np.clip(np.round(submission), 1, None).astype(int)

# 저장
test['call_count'] = submission
test.to_csv('250259.csv', index = False, encoding = 'cp949')